'use client'

import {useEffect,useMemo,useState} from 'react'
import {createClient} from '../../lib/supabase/client'

type RequestRow={id:string;start_date:string;end_date:string;start_time:string|null;end_time:string|null;reason:string;status:string;request_type:string;approval_role:string;decision_note:string|null;created_at:string}

const label=(type:string)=>type==='short_leave'?'Short Leave':type==='off'?'Staff Off':'Leave'

export default function TeacherLeaveRequests(){
 const db=createClient(); const [userId,setUserId]=useState(''); const [staffId,setStaffId]=useState(''); const [requests,setRequests]=useState<RequestRow[]>([]); const [type,setType]=useState<'leave'|'short_leave'|'off'>('leave'); const [startDate,setStartDate]=useState(''); const [endDate,setEndDate]=useState(''); const [startTime,setStartTime]=useState(''); const [endTime,setEndTime]=useState(''); const [reason,setReason]=useState(''); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false)
 const load=async()=>{const{data:{user}}=await db.auth.getUser();if(!user)return;setUserId(user.id);const{data:staff}=await db.from('staff').select('id').eq('profile_id',user.id).maybeSingle();if(!staff){setMessage('Your teacher account is not linked to a staff profile. Contact the administrator.');return}setStaffId(staff.id);const{data,error}=await db.from('leave_requests').select('id,start_date,end_date,start_time,end_time,reason,status,request_type,approval_role,decision_note,created_at').eq('staff_id',staff.id).order('created_at',{ascending:false});if(error)setMessage(error.message);else setRequests(data||[])}
 useEffect(()=>{load()},[])
 const needsTime=type==='short_leave'
 const needsDates=true
 const reset=()=>{setStartDate('');setEndDate('');setStartTime('');setEndTime('');setReason('')}
 const submit=async()=>{setMessage('');if(!staffId){setMessage('Staff profile not found.');return}if(!startDate||!endDate||!reason.trim()){setMessage('Please provide the date(s) and reason.');return}if(needsTime&&(!startTime||!endTime)){setMessage('Short leave requires a start and end time.');return}setLoading(true);const{error}=await db.from('leave_requests').insert({staff_id:staffId,start_date:startDate,end_date:endDate,start_time:needsTime?startTime:null,end_time:needsTime?endTime:null,reason:reason.trim(),request_type:type,approval_role:type==='off'?'hr':'headteacher',status:'pending'});setLoading(false);if(error)setMessage(error.message);else{setMessage('Request sent successfully.');reset();await load()}}
 const pending=useMemo(()=>requests.filter(x=>x.status==='pending'),[requests]);
 return <section className="prototype-panel" style={{marginTop:18}}><div className="prototype-panel-head"><div><h2>Leave & Off Requests</h2><p className="muted">Send leave, short leave or staff-off requests and track every decision.</p></div></div><div className="prototype-panel-body"><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}><label>Request type<select value={type} onChange={e=>setType(e.target.value as any)}><option value="leave">Leave</option><option value="short_leave">Short Leave</option><option value="off">Staff Off</option></select></label><label>Start date<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>End date{type==='short_leave'?<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/>:<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/>}</label>{needsTime&&<><label>Start time<input type="time" value={startTime} onChange={e=>setStartTime(e.target.value)}/></label><label>End time<input type="time" value={endTime} onChange={e=>setEndTime(e.target.value)}/></label></>}<label style={{gridColumn:'1/-1'}}>Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explain why you are requesting this leave/off" rows={3}/></label></div><div style={{marginTop:12}}><button className="btn" onClick={submit} disabled={loading}>{loading?'Sending…':'Send Request'}</button>{message&&<span className="muted" style={{marginLeft:12}}>{message}</span>}</div><div style={{marginTop:24}}><h3>My requests</h3><div className="prototype-table-wrap"><table className="prototype-table"><thead><tr><th>TYPE</th><th>DATE(S)</th><th>TIME</th><th>REASON</th><th>ROUTE</th><th>STATUS</th><th>DECISION</th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td><strong>{label(r.request_type)}</strong></td><td>{r.start_date}{r.end_date!==r.start_date?` → ${r.end_date}`:''}</td><td>{r.start_time&&r.end_time?`${r.start_time.slice(0,5)} – ${r.end_time.slice(0,5)}`:'—'}</td><td>{r.reason}</td><td>{r.approval_role==='headteacher'?'Head Teacher':'HR'}</td><td><strong>{r.status}</strong></td><td>{r.status==='rejected'?(r.decision_note||'Rejected by approver'):(r.status==='approved'?'Approved':'Awaiting decision')}</td></tr>)}{requests.length===0&&<tr><td colSpan={7} className="prototype-empty">No requests yet.</td></tr>}</tbody></table></div></div></div></section>
}
