'use client'
import {useEffect,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'}

export default function Page(){
 const db=createClient();const[tab,setTab]=useState('buses');const[routes,setRoutes]=useState<any[]>([]);const[vehicles,setVehicles]=useState<any[]>([]);const[students,setStudents]=useState<any[]>([]);const[assignments,setAssignments]=useState<any[]>([]);const[fees,setFees]=useState<any[]>([]);const[logs,setLogs]=useState<any[]>([]);const[tripOpen,setTripOpen]=useState(false);const[saving,setSaving]=useState(false);const[message,setMessage]=useState('');const[trip,setTrip]=useState({vehicle_id:'',route_name:'',amount:'',fuel_litres:'',description:''})
 const load=async()=>{const[r,v,s,a,f,l]=await Promise.all([db.from('transport_routes').select('*').order('route_name'),db.from('transport_vehicles').select('*').order('vehicle_no'),db.from('students').select('id,admission_number,first_name,last_name,class_id').eq('status','active').order('admission_number'),db.from('transport_assignments').select('*'),db.from('transport_fee_status').select('student_id,cleared,route_id'),db.from('transport_logs').select('*').order('log_date',{ascending:false}).limit(200)]);setRoutes(r.data||[]);setVehicles(v.data||[]);setStudents(s.data||[]);setAssignments(a.data||[]);setFees(f.data||[]);setLogs(l.data||[])}
 useEffect(()=>{void load()},[])
 const vehicleLabel=(id:string|null)=>vehicles.find(v=>v.id===id)?.vehicle_no||'—';const fuel=logs.filter(x=>x.log_type==='fuel');const maintenance=logs.filter(x=>['service','maintenance'].includes(x.log_type));const trips=logs.filter(x=>x.log_type==='trip');const holds=fees.filter(x=>x.cleared===false).length;const fuelTotal=fuel.reduce((n,x)=>n+Number(x.amount||0),0)
 const submitTrip=async()=>{if(!trip.vehicle_id||!trip.route_name){setMessage('Select a bus and route first.');return}setSaving(true);const{error}=await db.from('transport_logs').insert({vehicle_id:trip.vehicle_id,log_date:new Date().toISOString().slice(0,10),log_type:'trip',route_name:trip.route_name,amount:Number(trip.amount||0),fuel_litres:Number(trip.fuel_litres||0),description:trip.description||null});setSaving(false);setMessage(error?.message||'Trip recorded successfully.');if(!error){setTripOpen(false);setTrip({vehicle_id:'',route_name:'',amount:'',fuel_litres:'',description:''});await load()}}
 const tabs=[['buses','Buses & Drivers'],['assignments','Bus Assignments'],['trips','Daily Trips & Weekly'],['fuel','Fuel & Maintenance'],['emergencies','Emergencies']]
 return <main className="main"><div className="prototype-module"><header className="prototype-module-header"><div><h1>Transport</h1><p>Buses, drivers, routes, fuel, maintenance and emergency notifications</p></div><button className="prototype-primary-button" onClick={()=>setTripOpen(x=>!x)}>＋ Add Trip</button></header>
 <section className="prototype-kpis"><Kpi label="Buses" value={vehicles.length}/><Kpi label="Students on Buses" value={assignments.length}/><Kpi label="Fee-Hold on Bus" value={holds} tone="red" note="blocked from transport"/><Kpi label="Fuel Recorded" value={`KES ${fuelTotal.toLocaleString('en-KE')}`} tone="yellow"/></section>
 {message&&<div className="prototype-note">{message}</div>}
 {tripOpen&&<section className="prototype-panel"><div className="prototype-panel-head"><h2>Record Daily Trip</h2><button className="prototype-primary-button" onClick={submitTrip} disabled={saving}>{saving?'Saving…':'Save Trip'}</button></div><div className="prototype-panel-body"><div className="prototype-form-grid"><div><label>Bus</label><select value={trip.vehicle_id} onChange={e=>setTrip({...trip,vehicle_id:e.target.value})}><option value="">Select bus</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.vehicle_no} — {v.registration_no||'No registration'}</option>)}</select></div><div><label>Route</label><select value={trip.route_name} onChange={e=>setTrip({...trip,route_name:e.target.value})}><option value="">Select route</option>{routes.map(r=><option key={r.id} value={r.route_name}>{r.route_name}</option>)}</select></div><div><label>Fuel litres</label><input value={trip.fuel_litres} onChange={e=>setTrip({...trip,fuel_litres:e.target.value})}/></div><div><label>Trip / fuel cost (KES)</label><input value={trip.amount} onChange={e=>setTrip({...trip,amount:e.target.value})}/></div><div style={{gridColumn:'1/-1'}}><label>Notes</label><input value={trip.description} onChange={e=>setTrip({...trip,description:e.target.value})}/></div></div></div></section>}
 <nav className="prototype-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==='buses'&&<Panel title="Buses, Drivers & Routes"><Table headers={['PLATE','BUS','DRIVER','ROUTE','CAPACITY','STUDENTS','INSURANCE','STATUS']} rows={routes.map((r,i)=>{const v=vehicles.find(x=>x.vehicle_no===r.vehicle_no);return [v?.registration_no||r.vehicle_no||'—',r.route_name,r.driver_name||'—',r.route_name,r.capacity||'—',assignments.filter(a=>a.route_id===r.id).length,v?.insurance_expiry||'—',v?.status||'Active']})}/></Panel>}
 {tab==='assignments'&&<Panel title="Student Bus Assignments" note="Fee-hold students are clearly flagged and blocked from boarding."><Table headers={['ADM NO','STUDENT','ROUTE','FEE STATUS','BOARDING']} rows={assignments.map(a=>{const s=students.find(x=>x.id===a.student_id);const f=fees.find(x=>x.student_id===a.student_id);const r=routes.find(x=>x.id===a.route_id);return [s?.admission_number||'—',s?`${s.first_name} ${s.last_name}`:'—',r?.route_name||'—',f?.cleared?'Cleared':'Fee Hold',f?.cleared?'Allowed':'Blocked']})}/></Panel>}
 {tab==='trips'&&<Panel title="Daily Trips & Weekly Records"><Table headers={['TRIP','BUS','DATE','ROUTE','COST','NOTES']} rows={trips.map((x,i)=>[`TR-${String(i+1).padStart(2,'0')}`,vehicleLabel(x.vehicle_id),x.log_date,x.route_name||'—',`KES ${Number(x.amount||0).toLocaleString('en-KE')}`,x.description||'—'])}/></Panel>}
 {tab==='fuel'&&<><Panel title="Fuel Records"><Table headers={['BUS','COST','LITRES','DATE','DETAILS']} rows={fuel.map(x=>[vehicleLabel(x.vehicle_id),`KES ${Number(x.amount||0).toLocaleString('en-KE')}`,x.fuel_litres||0,x.log_date,x.description||'—'])}/></Panel><Panel title="Service & Maintenance Records"><Table headers={['BUS','DATE','TYPE','DETAILS']} rows={maintenance.map(x=>[vehicleLabel(x.vehicle_id),x.log_date,x.log_type,x.description||'—'])}/></Panel></>}
 {tab==='emergencies'&&<Panel title="Bus Emergencies & Delay Records" note="Record emergency or delay events in Transport Logs so the school can follow up with affected families."><Table headers={['BUS','DATE','ISSUE','DETAILS']} rows={logs.filter(x=>x.log_type==='emergency'||x.log_type==='delay').map(x=>[vehicleLabel(x.vehicle_id),x.log_date,x.log_type,x.description||'—'])}/></Panel>}
 </div></main>
}
function Kpi({label,value,tone='navy',note}:{label:string;value:any;tone?:string;note?:string}){return <div className={`prototype-kpi ${tone}`}><div className="prototype-kpi-icon">•</div><div><div className="prototype-kpi-label">{label}</div><div className="prototype-kpi-value">{value}</div>{note&&<div className="prototype-kpi-note">{note}</div>}</div></div>}
function Panel({title,children,note}:{title:string;children:React.ReactNode;note?:string}){return <section className="prototype-panel"><div className="prototype-panel-head"><h2>{title}</h2></div>{note&&<div className="prototype-note" style={{margin:'12px 16px 0'}}>{note}</div>}<div className="prototype-panel-body">{children}</div></section>}
function Table({headers,rows}:{headers:string[];rows:any[][]}){return <div className="prototype-table-wrap"><table className="prototype-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={headers.length} className="prototype-empty">No records have been recorded.</td></tr>}</tbody></table></div>}
