'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'

type Row={id:string;class_id:string;stream_id:string;day:string;start_time:string;end_time:string;learning_area_id:string|null;teacher_id:string|null;entry_type:string;break_name:string|null;confirmation_status:string}
const days=['Monday','Tuesday','Wednesday','Thursday','Friday']
const dayShort:Record<string,string>={Monday:'MON',Tuesday:'TUE',Wednesday:'WED',Thursday:'THU',Friday:'FRI'}
const fmt=(t?:string|null)=>t?t.slice(0,5):''

export default function Page(){
 const db=createClient()
 const[classes,setClasses]=useState<any[]>([]),[streams,setStreams]=useState<any[]>([]),[areas,setAreas]=useState<any[]>([]),[teachers,setTeachers]=useState<any[]>([]),[rows,setRows]=useState<Row[]>([])
 const[tab,setTab]=useState('builder'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 const[form,setForm]=useState({class_id:'',stream_id:'',teacher_id:'',learning_area_id:'',day:'Monday',start_time:'08:20',end_time:'08:55'})
 const[breakForm,setBreakForm]=useState({class_id:'',stream_id:'',day:'Monday',start_time:'09:30',end_time:'09:50',break_name:'BREAK'})
 const selectedClass=classes.find(x=>x.id===form.class_id)
 const classStreams=useMemo(()=>streams.filter(x=>x.class_id===form.class_id),[streams,form.class_id])
 const load=async()=>{setLoading(true);const [{data:c},{data:s},{data:a},{data:t},{data:r}]=await Promise.all([
   db.from('classes').select('id,name,level,class_teacher_id').eq('status','active').order('name'),
   db.from('streams').select('id,class_id,name').eq('status','active').order('name'),
   db.from('learning_areas').select('id,name,code').eq('active',true).order('name'),
   db.from('staff').select('id,profile_id,first_name,middle_name,last_name,job_title').eq('status','active').order('last_name'),
   db.from('timetables').select('id,class_id,stream_id,day,start_time,end_time,learning_area_id,teacher_id,entry_type,break_name,confirmation_status').order('start_time')
 ]);setClasses(c||[]);setStreams(s||[]);setAreas(a||[]);setTeachers((t||[]).filter(x=>/teacher|head teacher|deputy/i.test(String(x.job_title||''))));setRows((r||[]) as Row[]);setLoading(false)}
 useEffect(()=>{load()},[])
 useEffect(()=>{if(form.class_id&&!form.stream_id&&classStreams[0])setForm(x=>({...x,stream_id:classStreams[0].id}))},[form.class_id,classStreams])
 const saveLesson=async(e:any)=>{e.preventDefault();setSaving(true);setMessage('');if(!form.class_id||!form.stream_id||!form.learning_area_id||!form.start_time||!form.end_time){setMessage('Please select the class, stream, subject and times.');setSaving(false);return}if(form.end_time<=form.start_time){setMessage('End time must be after start time.');setSaving(false);return}
   const conflict=rows.find(x=>x.class_id===form.class_id&&x.stream_id===form.stream_id&&x.day===form.day&&x.entry_type==='lesson'&&form.start_time<x.end_time&&form.end_time>x.start_time)
   if(conflict){setMessage('This class already has a lesson in that time. Adjust the time before saving.');setSaving(false);return}
   const teacherConflict=rows.find(x=>x.teacher_id===form.teacher_id&&form.teacher_id&&x.day===form.day&&form.start_time<x.end_time&&form.end_time>x.start_time)
   if(teacherConflict){setMessage('That teacher is already scheduled at this time.');setSaving(false);return}
   const{error}=await db.from('timetables').insert({class_id:form.class_id,stream_id:form.stream_id,teacher_id:form.teacher_id||null,learning_area_id:form.learning_area_id,day:form.day,start_time:form.start_time,end_time:form.end_time,entry_type:'lesson',confirmation_status:'draft'});setMessage(error?.message||'Lesson added. The timetable is rebuilt automatically.');if(!error)await load();setSaving(false)}
 const saveBreak=async(e:any)=>{e.preventDefault();setSaving(true);setMessage('');const{error}=await db.from('timetables').insert({class_id:breakForm.class_id,stream_id:breakForm.stream_id,day:breakForm.day,start_time:breakForm.start_time,end_time:breakForm.end_time,entry_type:'break',break_name:breakForm.break_name||'BREAK',confirmation_status:'draft'});setMessage(error?.message||'Break added.');if(!error)await load();setSaving(false)}
 const confirmClass=async(classId:string,streamId:string)=>{setSaving(true);const{error}=await db.from('timetables').update({confirmation_status:'confirmed',confirmed_at:new Date().toISOString()}).eq('class_id',classId).eq('stream_id',streamId);setMessage(error?.message||'Class timetable confirmed.');if(!error)await load();setSaving(false)}
 const deleteRow=async(id:string)=>{if(!confirm('Remove this timetable entry?'))return;await db.from('timetables').delete().eq('id',id);await load()}
 const grouped=useMemo(()=>days.map(day=>({day,items:rows.filter(x=>x.day===day).sort((a,b)=>String(a.start_time).localeCompare(String(b.start_time)))})),[rows])
 const labelArea=(id:string|null)=>areas.find(x=>x.id===id)?.name||'—'
 const labelTeacher=(id:string|null)=>{const t=teachers.find(x=>x.id===id);return t?[t.first_name,t.middle_name,t.last_name].filter(Boolean).join(' '):'—'}
 const labelClass=(id:string)=>classes.find(x=>x.id===id)?.name||'—'
 const labelStream=(id:string)=>streams.find(x=>x.id===id)?.name||'—'
 const timetableGroups=useMemo(()=>Array.from(new Set(rows.map(x=>`${x.class_id}|${x.stream_id}`))),[rows])
 return <main className="main"><div className="prototype-module">
  <header className="prototype-module-header"><div><h1>Class Timetable</h1><p>Teachers enter the lessons they teach; the system automatically assembles the full weekly timetable.</p></div><button className="prototype-primary-button" onClick={()=>window.print()}>▣ Print Timetable</button></header>
  <section className="prototype-kpis"><div className="prototype-kpi navy"><div className="prototype-kpi-icon">▦</div><div><div className="prototype-kpi-label">Lesson Entries</div><div className="prototype-kpi-value">{rows.filter(x=>x.entry_type==='lesson').length}</div></div></div><div className="prototype-kpi green"><div className="prototype-kpi-icon">✓</div><div><div className="prototype-kpi-label">Confirmed</div><div className="prototype-kpi-value">{rows.filter(x=>x.confirmation_status==='confirmed').length}</div></div></div><div className="prototype-kpi blue"><div className="prototype-kpi-icon">♙</div><div><div className="prototype-kpi-label">Teachers</div><div className="prototype-kpi-value">{teachers.length}</div></div></div><div className="prototype-kpi yellow"><div className="prototype-kpi-icon">☕</div><div><div className="prototype-kpi-label">Breaks</div><div className="prototype-kpi-value">{rows.filter(x=>x.entry_type==='break').length}</div></div></div></section>
  <nav className="prototype-tabs">{[['builder','Teacher Lesson Entry'],['weekly','Auto-Built Timetable'],['breaks','Breaks'],['confirm','Class Teacher Confirmation']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {message&&<div className={`prototype-note ${message.toLowerCase().includes('error')||message.toLowerCase().includes('already')?'red':'green'}`} style={{margin:'12px 0'}}>{message}</div>}
  {tab==='builder'&&<section className="prototype-panel"><div className="prototype-panel-head"><div><h2>Teacher Lesson Entry</h2><div className="prototype-kpi-note">A teacher only enters the class, subject, day, start time and end time. All entries are automatically combined into the weekly timetable.</div></div></div><div className="prototype-panel-body"><form onSubmit={saveLesson} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10}}>
   <div><label>Class</label><select value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value,stream_id:''})} required><option value="">Select class…</option>{classes.map(x=><option key={x.id} value={x.id}>{x.name}{x.level?` — ${x.level}`:''}</option>)}</select></div>
   <div><label>Stream</label><select value={form.stream_id} onChange={e=>setForm({...form,stream_id:e.target.value})} required><option value="">Select stream…</option>{classStreams.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>
   <div><label>Teacher</label><select value={form.teacher_id} onChange={e=>setForm({...form,teacher_id:e.target.value})}><option value="">Current / assigned teacher</option>{teachers.map(x=><option key={x.id} value={x.id}>{[x.first_name,x.middle_name,x.last_name].filter(Boolean).join(' ')}</option>)}</select></div>
   <div><label>Subject / Learning area</label><select value={form.learning_area_id} onChange={e=>setForm({...form,learning_area_id:e.target.value})} required><option value="">Select subject…</option>{areas.map(x=><option key={x.id} value={x.id}>{x.name}{x.code?` (${x.code})`:''}</option>)}</select></div>
   <div><label>Day</label><select value={form.day} onChange={e=>setForm({...form,day:e.target.value})}>{days.map(x=><option key={x}>{x}</option>)}</select></div>
   <div><label>Start time</label><input type="time" value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})} required/></div>
   <div><label>End time</label><input type="time" value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})} required/></div>
   <div style={{display:'flex',alignItems:'end'}}><button className="prototype-primary-button" disabled={saving}>{saving?'Saving…':'＋ Add Lesson'}</button></div>
  </form></div></section>}
  {tab==='weekly'&&<section className="prototype-panel"><div className="prototype-panel-head"><div><h2>Auto-Built Weekly Timetable</h2><div className="prototype-kpi-note">Entries are sorted by day and time and checked for class and teacher clashes.</div></div></div><div className="prototype-table-wrap"><table className="prototype-table"><thead><tr><th>DAY</th><th>TIME</th><th>CLASS</th><th>STREAM</th><th>SUBJECT</th><th>TEACHER</th><th>STATUS</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={8}>Loading…</td></tr>:rows.length?grouped.flatMap(g=>g.items.map(x=><tr key={x.id}><td><strong>{dayShort[g.day]}</strong></td><td>{fmt(x.start_time)} – {fmt(x.end_time)}</td><td>{labelClass(x.class_id)}</td><td>{labelStream(x.stream_id)}</td><td>{x.entry_type==='break'?<strong>{x.break_name||'BREAK'}</strong>:labelArea(x.learning_area_id)}</td><td>{x.entry_type==='break'?'—':labelTeacher(x.teacher_id)}</td><td><span className={`prototype-badge ${x.confirmation_status==='confirmed'?'green':'yellow'}`}>{x.confirmation_status==='confirmed'?'Confirmed':'Draft'}</span></td><td><button type="button" onClick={()=>deleteRow(x.id)} style={{background:'transparent',border:0,color:'#b42318',cursor:'pointer'}}>Remove</button></td></tr>)):<tr><td colSpan={8} className="muted" style={{padding:30,textAlign:'center'}}>Teachers have not entered lessons yet.</td></tr>}</tbody></table></div></section>}
  {tab==='breaks'&&<section className="prototype-panel"><div className="prototype-panel-head"><div><h2>Class Breaks</h2><div className="prototype-kpi-note">The class teacher can add break periods after the lesson entries are assembled.</div></div></div><div className="prototype-panel-body"><form onSubmit={saveBreak} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10}}><div><label>Class</label><select value={breakForm.class_id} onChange={e=>setBreakForm({...breakForm,class_id:e.target.value,stream_id:''})} required><option value="">Select class…</option>{classes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div><label>Stream</label><select value={breakForm.stream_id} onChange={e=>setBreakForm({...breakForm,stream_id:e.target.value})} required><option value="">Select stream…</option>{streams.filter(x=>x.class_id===breakForm.class_id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div><label>Day</label><select value={breakForm.day} onChange={e=>setBreakForm({...breakForm,day:e.target.value})}>{days.map(x=><option key={x}>{x}</option>)}</select></div><div><label>Break name</label><input value={breakForm.break_name} onChange={e=>setBreakForm({...breakForm,break_name:e.target.value})} placeholder="BREAK / LUNCH"/></div><div><label>Start time</label><input type="time" value={breakForm.start_time} onChange={e=>setBreakForm({...breakForm,start_time:e.target.value})} required/></div><div><label>End time</label><input type="time" value={breakForm.end_time} onChange={e=>setBreakForm({...breakForm,end_time:e.target.value})} required/></div><div style={{display:'flex',alignItems:'end'}}><button className="prototype-primary-button" disabled={saving}>＋ Add Break</button></div></form></div></section>}
  {tab==='confirm'&&<section className="prototype-panel"><div className="prototype-panel-head"><div><h2>Class Teacher Confirmation</h2><div className="prototype-kpi-note">The class teacher reviews the automatically assembled timetable, adds breaks if needed, then confirms it.</div></div></div><div className="prototype-table-wrap"><table className="prototype-table"><thead><tr><th>CLASS</th><th>STREAM</th><th>ENTRIES</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{timetableGroups.map(g=>{const[a,b]=g.split('|');const group=rows.filter(x=>x.class_id===a&&x.stream_id===b);const confirmed=group.length>0&&group.every(x=>x.confirmation_status==='confirmed');return <tr key={g}><td>{labelClass(a)}</td><td>{labelStream(b)}</td><td>{group.length}</td><td><span className={`prototype-badge ${confirmed?'green':'yellow'}`}>{confirmed?'Confirmed':'Awaiting confirmation'}</span></td><td><button className="prototype-primary-button" type="button" disabled={saving||confirmed} onClick={()=>confirmClass(a,b)}>{confirmed?'Confirmed':'Confirm timetable'}</button></td></tr>})}</tbody></table></div></section>}
 </div></main>
}
