'use client'
import {useEffect,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'

export default function Page(){
 const [id,setId]=useState(''),[form,setForm]=useState({school_name:'',motto:'',address:'',phone:'',email:'',logo_url:'',currency:'KES',website:'',about:'',principal_message:'',admissions_text:''}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 const load=async()=>{const {data,error}=await createClient().from('school_settings').select('*').limit(1).maybeSingle();if(error)setMessage(error.message);else if(data){setId(data.id);setForm({school_name:data.school_name||'',motto:data.motto||'',address:data.address||'',phone:data.phone||'',email:data.email||'',logo_url:data.logo_url||'',currency:data.currency||'KES',website:data.website||'',about:data.about||'',principal_message:data.principal_message||'',admissions_text:data.admissions_text||''})}setLoading(false)}
 useEffect(()=>{load()},[])
 const save=async()=>{setSaving(true);setMessage('');const payload={...form,updated_at:new Date().toISOString()};const q=createClient().from('school_settings');const {error}=id?await q.update(payload).eq('id',id):await q.insert(payload);if(error)setMessage(error.message);else setMessage('School settings saved successfully.');setSaving(false);load()}
 const set=(k:string,v:string)=>setForm({...form,[k]:v})
 if(loading)return <main className="main"><h1>School Settings</h1><p className="muted">Loading…</p></main>
 return <main className="main"><header className="top"><div><h1 style={{margin:0}}>School Settings</h1><p className="muted">Manage the official AIC Cathedral school identity and public-facing content.</p></div></header><section className="card"><div className="form-grid">{[['school_name','School name'],['motto','Motto'],['address','Address'],['phone','Phone'],['email','Email'],['logo_url','Logo URL'],['currency','Currency'],['website','Website']].map(([k,l])=><div key={k}><label>{l}</label><input value={(form as any)[k]} onChange={e=>set(k,e.target.value)} /></div>)}</div><div style={{marginTop:12}}><label>About the school</label><textarea value={form.about} onChange={e=>set('about',e.target.value)} rows={4}/></div><div style={{marginTop:12}}><label>Headteacher / Principal message</label><textarea value={form.principal_message} onChange={e=>set('principal_message',e.target.value)} rows={4}/></div><div style={{marginTop:12}}><label>Admissions text</label><textarea value={form.admissions_text} onChange={e=>set('admissions_text',e.target.value)} rows={4}/></div>{message&&<p className={message.includes('successfully')?'success':'error'}>{message}</p>}<button className="btn" disabled={saving} onClick={save}>{saving?'Saving…':'Save school settings'}</button></section></main>
}
