import Link from 'next/link'
import { createClient } from '../../../../lib/supabase/server'
import EditStudentButton from '../edit-student-button'
import PassportPrintButton from './print-button'

export default async function LearnerPassport({searchParams}:{searchParams:Promise<{student?:string}>}){
 const params=await searchParams
 const s=await createClient()
 const [{data:students},{data:classes},{data:streams},{data:routes},{data:school}]=await Promise.all([
  s.from('students').select('id,admission_number,first_name,middle_name,last_name,gender,date_of_birth,admission_date,photo_url,status,nationality,religion,address,county,blood_group,allergies,medical_conditions,disability_special_needs,medication_notes,emergency_contact_name,emergency_contact_phone,emergency_contact_relationship,previous_school,birth_certificate_no,portal_code,uses_bus,bus_route,bus_pickup_point,class_id,stream_id').order('first_name'),
  s.from('classes').select('id,name'),s.from('streams').select('id,name'),s.from('transport_routes').select('id,route_name,vehicle_no,pickup_points'),s.from('school_settings').select('school_name,address,phone,email,logo_url,motto').single()
 ])
 const list=students||[], selected=list.find(x=>x.id===params.student)||list[0]
 if(!selected)return <main className="main"><h1>Digital Learner Passport</h1><div className="card">Add a learner first, then their digital passport will appear here.</div></main>
 const cls=classes?.find(x=>x.id===selected.class_id)?.name||'—', stream=streams?.find(x=>x.id===selected.stream_id)?.name||'—'
 const route=routes?.find(x=>x.id===selected.bus_route||x.route_name===selected.bus_route)
 const full=[selected.first_name,selected.middle_name,selected.last_name].filter(Boolean).join(' ')
 const logo='/aic-cathedral-official-logo.svg', schoolName=school?.school_name||'AIC Cathedral Primary School', address=school?.address||'P.O. Box 37, Gilgil'
 const Info=({label,value}:{label:string,value:any})=><div className="lp-info"><small>{label}</small><strong>{value||'—'}</strong></div>
 const Mini=({label,value}:{label:string,value:any})=><div className="id-mini"><small>{label}</small><b>{value||'—'}</b></div>
 return <main className="main learner-passport">
 <style>{`
 .learner-passport{--maroon:#8b1022;--gold:#e7ad22;--navy:#073b70}.lp-actions{display:flex;gap:9px;flex-wrap:wrap}.lp-actions .btn{width:auto;padding:11px 15px}.lp-hero{border-radius:22px;padding:22px;color:#fff;background:linear-gradient(135deg,#062d59,#1269a1);position:relative;overflow:hidden;box-shadow:0 18px 45px #082f5c22}.lp-hero:after{content:'';position:absolute;width:240px;height:240px;border:55px solid #fff1;border-radius:50%;right:-120px;top:-150px}.lp-brand{display:flex;align-items:center;gap:15px;position:relative;z-index:1}.lp-brand img{width:82px;height:82px;object-fit:contain;background:#fff;border-radius:14px;padding:5px}.lp-brand h2{margin:3px 0;font-size:25px}.lp-brand p{margin:3px 0;color:#dbeafe;font-size:12px}.lp-tag{display:inline-block;margin-top:16px;background:var(--maroon);padding:7px 13px;border-radius:999px;font-size:10px;font-weight:900;letter-spacing:1px}.lp-layout{display:grid;grid-template-columns:250px 1fr;gap:15px;margin-top:15px}.lp-list{position:sticky;top:20px;align-self:start}.lp-list h3{margin-top:0}.lp-list a{display:block;text-decoration:none;padding:10px;border-radius:10px;margin:5px 0;background:#f7f9fc}.lp-list a.active{background:#e7f1fb;border-left:4px solid #1269a1}.lp-card{background:#fff;border:1px solid #e2e8f0;border-radius:22px;padding:22px;box-shadow:0 10px 30px #0b1f3a0b}.lp-profile{display:grid;grid-template-columns:175px 1fr;gap:22px}.lp-photo{width:175px;aspect-ratio:3/4;border-radius:17px;border:4px solid var(--gold);overflow:hidden;background:#f4f7fb;display:grid;place-items:center;text-align:center}.lp-photo img{width:100%;height:100%;object-fit:cover}.lp-photo span{padding:15px;color:#6b7280;font-size:12px}.lp-name{font-size:34px;line-height:1.05;margin:0 0 12px;color:#102a4a}.lp-kicker{font-size:11px;font-weight:900;letter-spacing:2px;color:var(--maroon);margin:0 0 5px}.lp-code{display:inline-block;padding:7px 10px;border-radius:9px;background:#fff6da;border:1px solid #edd07a;color:#705000;font-size:11px;font-weight:900;margin-bottom:15px}.lp-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:13px}.lp-info small{display:block;text-transform:uppercase;letter-spacing:.5px;color:#7b8491;font-size:9px;margin-bottom:3px}.lp-info strong{display:block;font-size:13px;word-break:break-word}.lp-section{border-top:1px solid #e7ebf0;margin-top:22px;padding-top:18px}.lp-section h2{font-size:19px;color:#132f50;margin:0 0 13px}.lp-section h2:before{content:'';display:inline-block;width:5px;height:19px;background:var(--maroon);border-radius:5px;margin-right:8px;vertical-align:-3px}.lp-section-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.lp-note{margin-top:20px;padding:14px;border-radius:13px;background:#fffaf0;border:1px solid #ead38c;color:#536173;font-size:12px;line-height:1.55}
 .print-id-sheet{display:none}.print-id-page{width:210mm;height:297mm;display:grid;place-items:center;page-break-after:always}.print-id-page:last-child{page-break-after:auto}.id-card{width:85.6mm;height:53.98mm;border:1px solid #d5d9df;border-radius:3mm;overflow:hidden;position:relative;background:#fff;color:#172033;font-family:Arial,Helvetica,sans-serif}.id-head{height:17mm;background:linear-gradient(135deg,#062d59,#1269a1);color:#fff;padding:3mm 4mm;display:flex;gap:2.5mm;align-items:center}.id-head img{width:12mm;height:12mm;background:#fff;border-radius:2mm;padding:.6mm;object-fit:contain}.id-head b{font-size:7pt;display:block;line-height:1.05}.id-head span{font-size:4.7pt;color:#dbeafe;display:block;margin-top:1mm}.id-front-body{display:grid;grid-template-columns:25mm 1fr;gap:3mm;padding:2.7mm 4mm}.id-photo{width:25mm;height:30mm;object-fit:cover;border-radius:1.7mm;border:1mm solid var(--gold)}.id-empty{width:25mm;height:30mm;border:1mm solid var(--gold);border-radius:1.7mm;display:grid;place-items:center;text-align:center;font-size:5pt;color:#6b7280;background:#f5f7fa}.id-main h1{font-size:12pt;line-height:1;margin:0 0 1.7mm;color:#102a4a}.id-code{font-size:5.7pt;color:var(--maroon);font-weight:900;margin-bottom:2mm}.id-row{display:flex;gap:2mm;margin:1.25mm 0;font-size:5.3pt}.id-row b{width:20mm;color:#718096;font-weight:600}.id-row span{font-weight:800}.id-foot{position:absolute;bottom:0;left:0;right:0;height:4.3mm;background:var(--maroon);color:#fff;display:flex;justify-content:space-between;align-items:center;padding:0 4mm;font-size:4.7pt;font-weight:800}.id-back-head{height:12mm;background:var(--maroon);color:#fff;padding:2mm 4mm;display:flex;align-items:center;gap:2mm}.id-back-head img{width:8mm;height:8mm;background:#fff;border-radius:1.5mm;padding:.4mm;object-fit:contain}.id-back-head b{font-size:6.8pt}.id-back-head span{display:block;font-size:4.6pt;color:#ffe7a5;margin-top:.6mm}.id-back-body{padding:2.4mm 4mm}.id-back-grid{display:grid;grid-template-columns:1fr 1fr;gap:1.6mm 3mm}.id-mini{border-bottom:.2mm solid #e5e7eb;padding-bottom:.8mm}.id-mini small{display:block;color:#7b8491;font-size:4.2pt}.id-mini b{display:block;font-size:5pt;margin-top:.4mm;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.id-sign{display:grid;grid-template-columns:1fr 1fr;gap:5mm;margin-top:2.2mm}.id-sign div{border-top:.25mm solid #555;padding-top:1mm;text-align:center;color:#667085;font-size:4.4pt}.id-motto{text-align:center;color:var(--maroon);font-size:4.8pt;font-weight:900;margin-top:1.3mm}
 @media(max-width:900px){.lp-layout{grid-template-columns:1fr}.lp-list{position:static}.lp-grid{grid-template-columns:repeat(2,1fr)}.lp-section-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.lp-profile{grid-template-columns:1fr}.lp-photo{width:140px}.lp-name{font-size:28px}.lp-grid,.lp-section-grid{grid-template-columns:1fr}.lp-actions{width:100%}}
 @media print{@page{size:A4 portrait;margin:0}body{background:#fff!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}.sidebar,.top,.learner-passport>div:not(.print-id-sheet),.learner-passport>style{display:none!important}.dashboard{display:block!important;background:#fff!important}.main{padding:0!important;margin:0!important;max-width:none!important}.print-id-sheet{display:block!important}.id-card{box-shadow:none}}
 `}</style>
 <header className="top"><div><p className="muted" style={{marginBottom:4}}>STUDENT RECORD • DIGITAL PASSPORT</p><h1>Digital Learner Passport</h1><p className="muted">Official learner identity and school journey record.</p></div><div className="lp-actions"><EditStudentButton student={selected} classes={classes||[]} streams={streams||[]} routes={routes||[]}/><PassportPrintButton/></div></header>
 <div className="lp-layout"><aside className="card lp-list"><h3>Learners</h3>{list.map(x=><Link key={x.id} className={x.id===selected.id?'active':''} href={`/dashboard/students/passport?student=${x.id}`}><strong>{[x.first_name,x.middle_name,x.last_name].filter(Boolean).join(' ')}</strong><br/><small className="muted">{x.admission_number||'No admission no.'}</small></Link>)}</aside>
 <section><div className="lp-hero"><div className="lp-brand"><img src={logo} alt="AIC Cathedral official logo"/><div><div style={{fontSize:11,letterSpacing:1.4,fontWeight:900}}>AIC CATHEDRAL</div><h2>{schoolName}</h2><p>{address}</p>{school?.phone&&<p>{school.phone}{school.email?` • ${school.email}`:''}</p>}</div></div><div className="lp-tag">DIGITAL LEARNER PASSPORT • OFFICIAL RECORD</div></div>
 <div className="lp-card" style={{marginTop:14}}><div className="lp-profile"><div className="lp-photo">{selected.photo_url?<img src={selected.photo_url} alt={full}/>:<span>👤<br/><br/>Learner photo can be added with <b>Edit Passport</b>.</span>}</div><div><p className="lp-kicker">LEARNER</p><h1 className="lp-name">{full}</h1><div className="lp-code">SPECIAL CODE: {selected.portal_code||'—'}</div><div className="lp-grid"><Info label="Admission number" value={selected.admission_number}/><Info label="Grade / class" value={cls}/><Info label="Stream" value={stream}/><Info label="Gender" value={selected.gender}/><Info label="Date of birth" value={selected.date_of_birth}/><Info label="Admission date" value={selected.admission_date}/><Info label="Status" value={selected.status}/></div></div></div>
 <div className="lp-section"><h2>Personal & Family Information</h2><div className="lp-section-grid"><Info label="Nationality" value={selected.nationality}/><Info label="Religion" value={selected.religion}/><Info label="County" value={selected.county}/><Info label="Address" value={selected.address}/><Info label="Previous school" value={selected.previous_school}/><Info label="Birth certificate no." value={selected.birth_certificate_no}/><Info label="Emergency contact" value={selected.emergency_contact_name}/><Info label="Emergency phone" value={selected.emergency_contact_phone}/><Info label="Relationship" value={selected.emergency_contact_relationship}/></div></div>
 <div className="lp-section"><h2>Health & Support</h2><div className="lp-section-grid"><Info label="Blood group" value={selected.blood_group}/><Info label="Allergies" value={selected.allergies}/><Info label="Medical conditions" value={selected.medical_conditions}/><Info label="Disability / special needs" value={selected.disability_special_needs}/><Info label="Medication notes" value={selected.medication_notes}/></div></div>
 <div className="lp-section"><h2>Transport</h2><div className="lp-section-grid"><Info label="Uses school bus" value={selected.uses_bus?'Yes':'No'}/><Info label="Route" value={route?.route_name||selected.bus_route}/><Info label="Vehicle" value={route?.vehicle_no}/><Info label="Pickup point" value={selected.bus_pickup_point}/></div></div>
 <div className="lp-note"><b>School journey:</b> Results, CBC/CBE evidence, attendance, interventions, achievements, activities, finance and authorized transport history can remain connected to this learner record.</div></div></section></div>
 <div className="print-id-sheet" aria-hidden="true"><div className="print-id-page"><div className="id-card"><div className="id-head"><img src={logo} alt=""/><div><b>{schoolName}</b><span>{address}</span></div></div><div className="id-front-body"><div>{selected.photo_url?<img className="id-photo" src={selected.photo_url} alt=""/>:<div className="id-empty">LEARNER PHOTO</div>}</div><div className="id-main"><h1>{full}</h1><div className="id-code">DIGITAL LEARNER PASSPORT</div><div className="id-row"><b>Admission No.</b><span>{selected.admission_number||'—'}</span></div><div className="id-row"><b>Grade / Stream</b><span>{cls} / {stream}</span></div><div className="id-row"><b>Date of Birth</b><span>{selected.date_of_birth||'—'}</span></div><div className="id-row"><b>Gender</b><span>{selected.gender||'—'}</span></div><div className="id-row"><b>Special Code</b><span>{selected.portal_code||'—'}</span></div></div></div><div className="id-foot"><span>AIC CATHEDRAL</span><span>EDUCATION FOR EXCELLENCE</span></div></div></div>
 <div className="print-id-page"><div className="id-card"><div className="id-back-head"><img src={logo} alt=""/><div><b>AIC CATHEDRAL • STUDENT ID</b><span>Official learner identification card</span></div></div><div className="id-back-body"><div className="id-back-grid"><Mini label="Parent / Guardian" value={selected.emergency_contact_name}/><Mini label="Emergency Phone" value={selected.emergency_contact_phone}/><Mini label="Blood Group" value={selected.blood_group}/><Mini label="Allergies" value={selected.allergies||'None recorded'}/><Mini label="Medical / Support" value={selected.medical_conditions||selected.disability_special_needs||'None recorded'}/><Mini label="Transport" value={selected.uses_bus?(route?.route_name||selected.bus_route||'School bus'):'Not assigned'}/><Mini label="Pickup Point" value={selected.bus_pickup_point}/><Mini label="School Contact" value={school?.phone||'School office'}/></div><div className="id-sign"><div>School Secretary / Authorized Signatory</div><div>Official School Stamp</div></div><div className="id-motto">{school?.motto||'EDUCATION FOR EXCELLENCE'}</div></div></div></div></div>
 </main>
}
