'use client'
import{useState}from'react'
import{addStudent}from'./actions'
type ClassOption={id:string;name:string;level:string|null}
type RouteOption={id:string;route_name:string;vehicle_no:string|null;pickup_points:string|null}
export default function AdmissionForm({classes,routes=[]}:{classes:ClassOption[];routes?:RouteOption[]}){const[classId,setClassId]=useState('');const[usesBus,setUsesBus]=useState(false);const[selectedRoute,setSelectedRoute]=useState('');const route=routes.find(r=>r.id===selectedRoute);const pickup=route?.pickup_points||'';return <form action={addStudent} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12,marginTop:16}>
<input name="admission_number" placeholder="Admission No." required/><input name="first_name" placeholder="First name" required/><input name="middle_name" placeholder="Middle name"/><input name="last_name" placeholder="Last name" required/>
<select name="gender" required><option value="">Gender</option><option>Male</option><option>Female</option></select><input name="date_of_birth" type="date" aria-label="Date of birth"/>
<select name="class_id" value={classId} onChange={e=>setClassId(e.target.value)} required><option value="">Grade / Class</option>{classes.map(c=><option value={c.id} key={c.id}>{c.name}{c.level?` — ${c.level}`:''}</option>)}</select>
<select name="stream_name" aria-label="Stream"><option value="">Stream</option><option value="East">East</option><option value="West">West</option></select><input name="previous_school" placeholder="Previous school"/><input name="birth_certificate_no" placeholder="Birth certificate No."/>
<input name="nationality" placeholder="Nationality" defaultValue="Kenyan"/><input name="county" placeholder="County"/><input name="address" placeholder="Home address"/><select name="blood_group"><option value="">Blood group</option>{['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(x=><option key={x}>{x}</option>)}</select><input name="medical_conditions" placeholder="Medical information / special needs (if any)"/>
<div style={{gridColumn:'1/-1',borderTop:'1px solid #e5e7eb',paddingTop:14,marginTop:4}}><h3>School transport</h3><p className="muted">Buses and routes come directly from Transport Management. Add them there first and they will appear here automatically.</p></div>
<label style={{display:'flex',gap:8,alignItems:'center'}}><input type="checkbox" name="uses_bus" checked={usesBus} onChange={e=>{setUsesBus(e.target.checked);if(!e.target.checked)setSelectedRoute('')}} style={{width:18,height:18}}/> Learner uses school bus</label>
<select name="bus_route" value={selectedRoute} disabled={!usesBus} onChange={e=>setSelectedRoute(e.target.value)}><option value="">Select saved bus route</option>{routes.map(r=><option key={r.id} value={r.id}>{r.route_name}{r.vehicle_no?` — Bus ${r.vehicle_no}`:''}</option>)}</select>
<input name="bus_pickup_point" placeholder={pickup?'Pickup point (route points loaded)':'Pickup / drop-off point'} defaultValue={pickup} disabled={!usesBus}/>
<input name="emergency_contact_name" placeholder="Emergency contact name"/><input name="emergency_contact_phone" placeholder="Emergency contact phone"/><input name="emergency_contact_relationship" placeholder="Emergency relationship"/>
<div style={{gridColumn:'1/-1',borderTop:'1px solid #e5e7eb',paddingTop:14,marginTop:4}}><h3>Primary parent / guardian</h3></div>
<input name="parent_name" placeholder="Parent / guardian full name" required/><input name="parent_phone" placeholder="Parent phone" required/><input name="parent_email" type="email" placeholder="Parent email"/><input name="parent_occupation" placeholder="Occupation"/><input name="parent_id_number" placeholder="National ID / document No."/><select name="parent_relationship" required><option value="">Relationship</option><option value="Father">Father</option><option value="Mother">Mother</option></select>
<div style={{gridColumn:'1/-1',borderTop:'1px solid #e5e7eb',paddingTop:14,marginTop:4}}><h3>Second parent / guardian (optional)</h3></div>
<input name="parent2_name" placeholder="Second guardian full name"/><input name="parent2_phone" placeholder="Second guardian phone"/><input name="parent2_email" type="email" placeholder="Second guardian email"/><input name="parent2_occupation" placeholder="Occupation"/><select name="parent2_relationship"><option value="">Relationship</option><option value="Father">Father</option><option value="Mother">Mother</option></select>
<div style={{gridColumn:'1/-1'}}><button className="btn">Add complete student record</button></div></form>}
