import Link from 'next/link'
import {createClient} from '../lib/supabase/server'

export default async function Home(){
 const s=await createClient();const[{data:settings},{data:news}]=await Promise.all([s.from('school_settings').select('school_name,motto,phone,email,address,about,principal_message').limit(1).maybeSingle(),s.from('announcements').select('id,title,body,created_at').eq('published',true).eq('audience','all').order('created_at',{ascending:false}).limit(3)])
 const school=settings?.school_name||'AIC Cathedral Primary School';const motto=settings?.motto||'Growing in faith, knowledge and character.'
 return <main className="site"><nav className="site-nav"><Link href="/" className="site-brand"><span className="site-logo">AIC</span><span><strong>{school}</strong><small>Excellence • Faith • Character</small></span></Link><div className="site-links"><a href="#about">About</a><a href="#academics">Academics</a><a href="#admissions">Admissions</a><a href="#news">News</a><a href="#contact">Contact</a><Link href="/login" className="site-login">ERP Login</Link></div></nav>
 <section className="hero"><div className="hero-copy"><span className="eyebrow">AIC CATHEDRAL PRIMARY SCHOOL</span><h1>Learning today. <span>Leading tomorrow.</span></h1><p>{motto}</p><div className="hero-actions"><a className="site-btn" href="#admissions">Admissions</a><a className="site-btn secondary" href="#about">Discover our school</a></div></div><div className="hero-panel"><div className="hero-badge">AIC</div><h2>Faith-led education</h2><p>We nurture confident, responsible learners through strong academics, values and a caring school community.</p></div></section>
 <section id="about" className="site-section"><div className="section-heading"><span>WHO WE ARE</span><h2>A school built around the whole child</h2></div><div className="feature-grid"><article><b>01</b><h3>Strong academics</h3><p>Structured learning, assessment and CBC-focused development help every learner progress with confidence.</p></article><article><b>02</b><h3>Character & faith</h3><p>We cultivate integrity, respect, responsibility, service and a strong Christian foundation.</p></article><article><b>03</b><h3>Every learner matters</h3><p>A supportive environment where learners can discover their gifts, build confidence and belong.</p></article></div>{settings?.about&&<p className="about-copy">{settings.about}</p>}</section>
 <section id="academics" className="site-section tinted"><div className="section-heading"><span>ACADEMICS</span><h2>Preparing learners for the future</h2></div><div className="program-grid"><div><h3>Competency Based Curriculum</h3><p>Learning experiences that develop knowledge, skills, values and competencies.</p></div><div><h3>Co-curricular growth</h3><p>Sport, creativity, leadership and teamwork complement classroom learning.</p></div><div><h3>Safe school community</h3><p>Clear pastoral support, attendance and communication help learners thrive.</p></div></div></section>
 <section id="admissions" className="site-section admissions"><div><span>ADMISSIONS</span><h2>Start your child's journey with us</h2><p>{settings?.admissions_text||'Contact the school office for current admission requirements, available places, fees and a school visit.'}</p></div><a className="site-btn" href={`mailto:${settings?.email||'info@aiccathedral.ac.ke'}`}>Contact admissions</a></section>
 <section id="news" className="site-section"><div className="section-heading"><span>NEWS & NOTICES</span><h2>From our school community</h2></div><div className="news-grid">{news?.length?news.map(n=><article key={n.id}><small>{new Date(n.created_at).toLocaleDateString()}</small><h3>{n.title}</h3><p>{n.body}</p></article>):<article><h3>Welcome to AIC Cathedral Primary School</h3><p>School announcements will appear here as the administration publishes them.</p></article>}</div></section>
 <section id="contact" className="contact-band"><div><span>GET IN TOUCH</span><h2>{school}</h2><p>{settings?.address||'AIC Cathedral Primary School'}</p></div><div><p>{settings?.phone||'School office'}</p><p>{settings?.email||'info@aiccathedral.ac.ke'}</p></div></section>
 <footer className="site-footer"><span>© {new Date().getFullYear()} {school}</span><Link href="/login">Staff ERP Login</Link></footer>
 </main>
}