'use client'
import { useEffect, useState } from 'react'
import { createClient } from '../../../lib/supabase/client'

type Req={id:string;item_name:string;quantity:number;estimated_cost:number;status:string;created_at:string;request_date:string}
type Supplier={id:string;name:string;phone:string|null;email:string|null;address:string|null;tax_pin:string|null}
type Lpo={id:string;lpo_no:string;requisition_no:string|null;supplier_id:string|null;supplier_name:string;item_name:string;quantity:number;unit_price:number;amount:number;description:string|null;delivery_date:string|null;terms:string|null;status:string;created_at:string}
const money=(n:number)=>`KES ${Number(n||0).toLocaleString('en-KE')}`
const esc=(v:any)=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))

export default function LpoManager(){
 const db=createClient()
 const[reqs,setReqs]=useState<Req[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[lpos,setLpos]=useState<Lpo[]>([]),[supplierByReq,setSupplierByReq]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[logo,setLogo]=useState('')
 const load=async()=>{const[{data:r},{data:s},{data:l},{data:settings}]=await Promise.all([db.from('procurement_requests').select('id,item_name,quantity,estimated_cost,status,created_at,request_date').eq('status','approved').order('created_at',{ascending:false}),db.from('suppliers').select('id,name,phone,email,address,tax_pin').eq('status','active').order('name'),db.from('procurement_lpos').select('*').order('created_at',{ascending:false}),db.from('school_settings').select('logo_url').limit(1).maybeSingle()]);setReqs((r||[]) as Req[]);setSuppliers((s||[]) as Supplier[]);setLpos((l||[]) as Lpo[]);setLogo(settings?.logo_url||'');if(!l||!r)setMessage('Could not load procurement documents.')}
 useEffect(()=>{void load()},[])
 const generate=async(r:Req)=>{setBusy(true);setMessage('');const{data,error}=await db.rpc('generate_lpo_from_requisition',{p_request_id:r.id,p_created_by:(await db.auth.getUser()).data.user?.id||null});if(error)setMessage(error.message);else{const chosen=supplierByReq[r.id];if(chosen&&data?.id){const supplier=suppliers.find(s=>s.id===chosen);await db.from('procurement_lpos').update({supplier_id:chosen,supplier_name:supplier?.name||'Supplier to be selected'}).eq('id',data.id)}setMessage(`LPO ${data?.lpo_no||''} generated successfully.`);setSupplierByReq(x=>({...x,[r.id]:''}));await load()}setBusy(false)}
 const printLpo=(l:Lpo)=>{const s=suppliers.find(x=>x.id===l.supplier_id);const requisitionName=l.item_name;const body=`<div class="meta"><b>LPO No:</b> ${esc(l.lpo_no)} &nbsp; <b>Date:</b> ${esc(l.created_at?.slice(0,10))}</div><table><tbody><tr><th>Supplier</th><td>${esc(s?.name||l.supplier_name)}</td></tr><tr><th>Supplier contact</th><td>${esc(s?.phone||s?.email)}</td></tr><tr><th>KRA PIN</th><td>${esc(s?.tax_pin)}</td></tr><tr><th>Requisition</th><td>${esc(requisitionName)}</td></tr></tbody></table><table><thead><tr><th>Item / Service</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr></thead><tbody><tr><td>${esc(l.item_name)}</td><td>${esc(l.quantity)}</td><td>${money(l.unit_price)}</td><td>${money(l.amount)}</td></tr></tbody></table><div class="box"><b>Description</b><p>${esc(l.description)}</p><b>Delivery date</b><p>${esc(l.delivery_date)}</p><b>Terms</b><p>${esc(l.terms)}</p></div><div class="sign"><span>Prepared by: __________________</span><span>Approved by: __________________</span></div>`;const w=window.open('','_blank','width=900,height=900');if(!w)return;w.document.write(`<!doctype html><html><head><title>${esc(l.lpo_no)}</title><style>@page{margin:15mm}body{font-family:Arial,sans-serif;color:#172033;padding:28px}header{display:flex;gap:15px;align-items:center;border-bottom:5px solid #b8860b;padding-bottom:14px}header img{width:72px;height:72px;object-fit:contain}h1{margin:0;color:#12385d;font-size:25px}.meta{font-size:12px;color:#667085;margin:8px 0}table{width:100%;border-collapse:collapse;margin:15px 0}th,td{border:1px solid #d0d7e2;padding:10px;text-align:left;font-size:12px}th{background:#12385d;color:#fff}.box{border:1px solid #d8e0ea;border-radius:10px;padding:14px;margin-top:16px}.sign{display:flex;justify-content:space-between;margin-top:45px;font-size:12px}@media print{body{padding:0}}</style></head><body><header>${logo?`<img src="${esc(logo)}" alt="School logo">`:''}<div><h1>LOCAL PURCHASE ORDER</h1><div class="meta">AIC CATHEDRAL PRIMARY SCHOOL</div></div></header>${body}<script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body></html>`);w.document.close()}
 return <section className="card"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h2 style={{margin:0}}>Automatic LPOs</h2><p className="muted">Approved requisitions generate unique LPO numbers automatically. Select a supplier from Procurement, then print or save the LPO as PDF.</p></div></div>{message&&<p>{message}</p>}<div style={{marginTop:16}}><h3>Approved requisitions ready for LPO</h3>{reqs.length?reqs.map(r=><div key={r.id} style={{display:'grid',gridTemplateColumns:'2fr 1fr auto',gap:10,alignItems:'center',padding:'12px 0',borderBottom:'1px solid #edf0f4'}}><div><strong>{r.item_name}</strong><div className="muted">Date {r.request_date} · Qty {r.quantity} · Estimated {money(r.estimated_cost)}</div></div><select value={supplierByReq[r.id]||''} onChange={e=>setSupplierByReq(x=>({...x,[r.id]:e.target.value}))}><option value="">Supplier from Procurement</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button className="btn" disabled={busy} onClick={()=>generate(r)}>Generate LPO</button></div>):<p className="muted">No approved requisitions waiting for an LPO.</p>}</div><div style={{marginTop:24,overflowX:'auto'}}><h3>Generated LPOs</h3><table className="prototype-table"><thead><tr><th>LPO No.</th><th>Requisition</th><th>Supplier</th><th>Item</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{lpos.length?lpos.map(l=><tr key={l.id}><td><strong>{l.lpo_no}</strong></td><td>{l.item_name||'—'}</td><td>{l.supplier_name||'—'}</td><td>{l.item_name}</td><td>{money(l.amount)}</td><td>{l.status}</td><td><button className="btn secondary" onClick={()=>printLpo(l)}>🖨 Download / Print</button></td></tr>):<tr><td colSpan={7} className="prototype-empty">No LPOs generated yet.</td></tr>}</tbody></table></div><style jsx>{`@media(max-width:800px){div[style*="grid-template-columns:2fr 1fr auto"]{grid-template-columns:1fr!important}}`}</style></section>}
