import RequisitionManager from './requisition-manager'
import SimpleCrud from '../_components/simple-crud'
import {PrototypePage} from '../_components/prototype-workspace'
import LpoManager from './lpo-manager'
import LowStockAlerts from './low-stock-alerts'
const cats=['Kitchen','Stationery','Spares','General inventory']
function ProcurementSection(){return <PrototypePage title="Procurement" subtitle="Requisitions, approvals, suppliers and procurement documents in one controlled workflow." tabs={[["#requisitions","Requisitions"],["#documents","LPOs & Job Cards"],["#suppliers","Suppliers"],["#approvals","Approvals"]]}><section id="requisitions"><RequisitionManager mode="requester"/></section><section id="documents"><LpoManager/><div style={{marginTop:20}}><SimpleCrud table="procurement_documents" title="Job Cards & Invoices" fields={[{name:'document_type',label:'Document',options:['Job Card','Invoice','Delivery Note']},{name:'document_no',label:'Document No.'},{name:'amount',label:'Amount',type:'number'},{name:'status',label:'Status',options:['draft','generated','approved','received','paid']}]} /></div></section><section id="suppliers"><SimpleCrud table="suppliers" title="Supplier details" fields={[{name:'name',label:'Supplier name',required:true},{name:'service_description',label:'Description of services / what they supply',required:true},{name:'contact_person',label:'Contact person'},{name:'phone',label:'Phone'},{name:'email',label:'Email'},{name:'tax_pin',label:'KRA PIN'},{name:'address',label:'Address'},{name:'status',label:'Status',options:['active','inactive']}]} /></section><section id="approvals"><RequisitionManager mode="approval"/></section></PrototypePage>}
function InventorySection(){return <PrototypePage title="Inventory" subtitle="Choose one inventory function at a time. Item IDs are not shown." tabs={[["#all-items","Stock Register"],["#stock-in","Stock In"],["#low-stock","Low-Stock Alerts"]]}><section id="all-items"><SimpleCrud table="inventory_items" title="Stock register" fields={[{name:'item_name',label:'Item name',required:true},{name:'category',label:'Store category',options:cats},{name:'quantity',label:'Quantity',type:'number',required:true},{name:'unit',label:'Unit'},{name:'reorder_level',label:'Reorder level',type:'number'}]} /></section><section id="stock-in"><SimpleCrud table="inventory_transactions" title="Stock in" fields={[{name:'item_name',label:'Item name',required:true},{name:'transaction_type',label:'Movement',options:['received']},{name:'quantity',label:'Quantity received',type:'number',required:true},{name:'note',label:'Note'}]} /></section><section id="low-stock"><LowStockAlerts/></section></PrototypePage>}
export default function Page(){return <PrototypePage title="Procurement & Inventory" subtitle="Procurement follows submit → Procurement Officer approval → LPO/document stage. Inventory remains separate." tabs={[["#procurement","Procurement"],["#inventory","Inventory"]]}><section id="procurement"><ProcurementSection/></section><section id="inventory"><InventorySection/></section></PrototypePage>}
