import SimpleCrud from '../_components/simple-crud'
import { PrototypePage } from '../_components/prototype-workspace'
export default function Page(){return <PrototypePage title="Procurement" subtitle="Requisitions, approvals, LPOs, job cards, suppliers and invoices" action={<a href="#requisitions" className="prototype-primary-button">+ New Requisition</a>} kpis={[{label:'Pending Requisitions',value:'Live',note:'Awaiting approval',tone:'yellow'},{label:'Approved',value:'Live',note:'Authorized requests',tone:'green'},{label:'Active LPOs',value:'Live',note:'Generated documents',tone:'navy'},{label:'Suppliers',value:'Live',note:'Supplier register',tone:'blue'}]} tabs={[["#requisitions","Requisitions"],["#documents","LPOs & Job Cards"],["#suppliers","Suppliers"],["#invoices","Procurement Invoices"],["#authorized","Authorized Users"]]}>
 <section id="requisitions"><SimpleCrud table="procurement_requests" title="Requisitions" fields={[{name:'item_name',label:'Item / service',required:true},{name:'quantity',label:'Quantity',type:'number',required:true},{name:'estimated_cost',label:'Estimated cost',type:'number',required:true},{name:'status',label:'Approval status',options:['pending','approved','ordered','received','rejected']}]} roleHint="Approved requisitions feed the existing LPO / job-card automation."/></section>
 <section id="documents"><SimpleCrud table="procurement_documents" title="LPOs, job cards, invoices & delivery" fields={[{name:'request_id',label:'Requisition ID',required:true},{name:'document_type',label:'Document',options:['LPO','Job Card','Invoice','Delivery Note']},{name:'document_no',label:'Document No.'},{name:'supplier_id',label:'Supplier ID'},{name:'amount',label:'Amount',type:'number'},{name:'status',label:'Status',options:['draft','generated','approved','received','paid']}]} /></section>
 <section id="suppliers"><SimpleCrud table="suppliers" title="Supplier details" fields={[{name:'name',label:'Supplier name',required:true},{name:'contact_person',label:'Contact person'},{name:'phone',label:'Phone'},{name:'email',label:'Email'},{name:'tax_pin',label:'KRA PIN'},{name:'address',label:'Address'},{name:'status',label:'Status',options:['active','inactive']}]} /></section>
 <section id="invoices"><SimpleCrud table="procurement_approvals" title="Procurement approvals / invoice decisions" fields={[{name:'request_id',label:'Requisition ID',required:true},{name:'approver_id',label:'Approver user ID'},{name:'decision',label:'Decision',options:['pending','approved','rejected']},{name:'comments',label:'Comments'}]} /></section>
 <section id="authorized" className="prototype-panel"><div className="prototype-panel-head"><h2>Authorized procurement users</h2></div><div className="prototype-panel-body"><p className="muted">Approval limits remain controlled by the existing user/role workflow. This workspace does not change the database permissions.</p></div></section>
 </PrototypePage>}
