'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'
type Props={mode?:'requester'|'approval'}
type Term={id:string;name:string;academic_year_id:string}
type Year={id:string;year:number;is_current:boolean;status:string}
type Req={id:string;requisition_no:string;item_name:string;quantity:number;estimated_cost:number;status:string;request_date:string;week_no:number|null;term_id:string|null;academic_year_id:string|null;requested_by:string|null;approved_by:string|null}
type Profile={id:string;full_name:string|null;role:string}
const money=(n:number)=>'KES '+Number(n||0).toLocaleString('en-KE')
const esc=(v:any)=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))
const printDoc=(title:string,body:string)=>{const w=window.open('','_blank','width=1000,height=900');if(!w)return;w.document.write('<!doctype html><html><head><title>'+esc(title)+'</title><style>@page{margin:12mm}body{font-family:Arial;padding:24px;color:#172033}h1{color:#12385d;border-bottom:4px solid #b8860b;padding-bottom:12px}table{width:100%;border-collapse:collapse;margin:14px 0}th,td{border:1px solid #d5dce7;padding:8px;font-size:11px;text-align:left}th{background:#12385d;color:#fff}.group{margin-top:22px;page-break-inside:avoid}.group h2{color:#12385d}</style></head><body><h1>AIC CATHEDRAL COMPREHENSIVE SCHOOL</h1>'+body+'<script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body></html>');w.document.close()}
export default function RequisitionManager({mode='requester'}:Props){
 const db=createClient();const[years,setYears]=useState<Year[]>([]),[terms,setTerms]=useState<Term[]>([]),[reqs,setReqs]=useState<Req[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[uid,setUid]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[termFilter,setTermFilter]=useState('all'),[weekFilter,setWeekFilter]=useState('all'),[comments,setComments]=useState<Record<string,string>>({}),[form,setForm]=useState({item_name:'',quantity:'1',estimated_cost:'',request_date:new Date().toISOString().slice(0,10),academic_year_id:'',term_id:'',week_no:'1'})
 const load=async()=>{const[a,b,c,d,authResult]=await Promise.all([db.from('academic_years').select('id,year,is_current,status').eq('status','active').order('year',{ascending:false}),db.from('terms').select('id,name,academic_year_id').order('start_date'),db.from('procurement_requests').select('id,requisition_no,item_name,quantity,estimated_cost,status,request_date,week_no,term_id,academic_year_id,requested_by,approved_by').order('created_at',{ascending:false}),db.from('profiles').select('id,full_name,role'),db.auth.getUser()]);setYears((a.data||[]) as Year[]);setTerms((b.data||[]) as Term[]);setReqs((c.data||[]) as Req[]);setProfiles((d.data||[]) as Profile[]);setUid(authResult.data?.user?.id||null);const y=(a.data||[]).find((x:any)=>x.is_current)||a.data?.[0];const t=(b.data||[]).find((x:any)=>x.academic_year_id===y?.id);if(y)setForm(f=>({...f,academic_year_id:f.academic_year_id||y.id,term_id:f.term_id||t?.id||''}))}
 useEffect(()=>{void load();const handler=(e:Event)=>{const item=(e as CustomEvent).detail?.item;if(typeof item==='string')setForm(f=>({...f,item_name:item,quantity:'1',estimated_cost:''}))};window.addEventListener('inventory:create-requisition',handler);return()=>window.removeEventListener('inventory:create-requisition',handler)},[])
 const officer=profiles.find(p=>p.id===uid)?.role==='procurement_officer';const termName=(id:string|null)=>terms.find(t=>t.id===id)?.name||'—';const person=(id:string|null)=>profiles.find(p=>p.id===id)?.full_name||'—';const approved=reqs.filter(r=>r.status==='approved');const filtered=useMemo(()=>approved.filter(r=>(termFilter==='all'||r.term_id===termFilter)&&(weekFilter==='all'||String(r.week_no)===weekFilter)),[approved,termFilter,weekFilter])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');const{data,error}=await db.rpc('submit_procurement_requisition',{p_item_name:form.item_name,p_quantity:Number(form.quantity),p_estimated_cost:Number(form.estimated_cost),p_request_date:form.request_date,p_academic_year_id:form.academic_year_id,p_term_id:form.term_id,p_week_no:Number(form.week_no)});setMessage(error?error.message:'Requisition '+(data?.requisition_no||'')+' submitted to Procurement Officer.');if(!error){setForm(f=>({...f,item_name:'',quantity:'1',estimated_cost:''}));await load()}setBusy(false)}
 const decide=async(r:Req,d:'approved'|'rejected')=>{setBusy(true);setMessage('');const{data,error}=await db.rpc('approve_procurement_requisition',{p_request_id:r.id,p_decision:d,p_comments:comments[r.id]||null});setMessage(error?error.message:'Requisition '+(data?.requisition_no||r.requisition_no)+' '+d+'.');if(!error)await load();setBusy(false)}
 const printOne=(r:Req)=>printDoc('Requisition '+r.requisition_no,'<div><b>Requisition No:</b> '+esc(r.requisition_no)+'<br><b>Term:</b> '+esc(termName(r.term_id))+'<br><b>Week:</b> Week '+esc(r.week_no)+'<br><b>Requested by:</b> '+esc(person(r.requested_by))+'</div><table><tr><th>Item / Service</th><th>Quantity</th><th>Estimated cost</th></tr><tr><td>'+esc(r.item_name)+'</td><td>'+esc(r.quantity)+'</td><td>'+money(r.estimated_cost)+'</td></tr></table><p>Approved by: '+esc(person(r.approved_by))+'</p>')
 const printAll=()=>{const groups=new Map<string,Req[]>();filtered.forEach(r=>{const k=termName(r.term_id)+' — Week '+r.week_no;groups.set(k,(groups.get(k)||[]).concat(r))});let body='<p>Approved requisitions: '+filtered.length+'</p>';groups.forEach((rows,k)=>{body+='<div class="group"><h2>'+esc(k)+'</h2><table><tr><th>Requisition No.</th><th>Date</th><th>Requested by</th><th>Item / Service</th><th>Qty</th><th>Estimated</th></tr>'+rows.map(r=>'<tr><td>'+esc(r.requisition_no)+'</td><td>'+esc(r.request_date)+'</td><td>'+esc(person(r.requested_by))+'</td><td>'+esc(r.item_name)+'</td><td>'+esc(r.quantity)+'</td><td>'+money(r.estimated_cost)+'</td></tr>').join('')+'</table></div>'});printDoc('Approved Procurement Requisitions',body)}
 const showForm=mode==='requester';const showApproval=mode==='approval'
 return <div>{showForm&&<section className="card"><h2>Requisitions</h2><p className="muted">Head Teacher and other permitted users can send requisitions. The number is automatic.</p><form onSubmit={submit} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10}}><div><label>Item / service</label><input required value={form.item_name} onChange={e=>setForm({...form,item_name:e.target.value})}/></div><div><label>Quantity</label><input required min="1" type="number" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></div><div><label>Estimated cost</label><input required min="0" type="number" value={form.estimated_cost} onChange={e=>setForm({...form,estimated_cost:e.target.value})}/></div><div><label>Date</label><input required type="date" value={form.request_date} onChange={e=>setForm({...form,request_date:e.target.value})}/></div><div><label>Academic year</label><select required value={form.academic_year_id} onChange={e=>setForm({...form,academic_year_id:e.target.value,term_id:''})}><option value="">Select year…</option>{years.map(y=><option key={y.id} value={y.id}>{y.year}{y.is_current?' (Current)':''}</option>)}</select></div><div><label>Term</label><select required value={form.term_id} onChange={e=>setForm({...form,term_id:e.target.value})}><option value="">Select term…</option>{terms.filter(t=>!form.academic_year_id||t.academic_year_id===form.academic_year_id).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div><label>Week</label><select required value={form.week_no} onChange={e=>setForm({...form,week_no:e.target.value})}>{[1,2,3,4].map(w=><option key={w} value={w}>Week {w}</option>)}</select></div><div><button className="btn" disabled={busy}>{busy?'Saving…':'Send Requisition'}</button></div></form>{message&&<p>{message}</p>}</section>}
 {showApproval&&<><section className="card"><h2>Pending Procurement Approval</h2><p className="muted">Only the Procurement Officer role can approve or reject. Head Teacher can submit but cannot approve procurement.</p><div style={{overflowX:'auto'}}><table className="prototype-table"><thead><tr><th>Requisition</th><th>Term</th><th>Week</th><th>Date</th><th>Requested by</th><th>Item</th><th>Qty</th><th>Estimated</th><th>Action</th></tr></thead><tbody>{reqs.filter(r=>r.status==='pending').map(r=><tr key={r.id}><td><strong>{r.requisition_no}</strong></td><td>{termName(r.term_id)}</td><td>Week {r.week_no}</td><td>{r.request_date}</td><td>{person(r.requested_by)}</td><td>{r.item_name}</td><td>{r.quantity}</td><td>{money(r.estimated_cost)}</td><td>{officer?<><input placeholder="Optional comment" value={comments[r.id]||''} onChange={e=>setComments({...comments,[r.id]:e.target.value})}/><button className="btn" disabled={busy} onClick={()=>decide(r,'approved')}>Approve</button><button className="btn secondary" disabled={busy} onClick={()=>decide(r,'rejected')}>Reject</button></>:<span className="muted">Procurement Officer only</span>}</td></tr>)}</tbody></table></div>{!reqs.some(r=>r.status==='pending')&&<p className="muted">No pending requisitions.</p>}{message&&<p>{message}</p>}</section><section className="card"><div style={{display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><h2>Approved Requisitions — Print by Term & Week</h2><p className="muted">Term One, Term Two, Term Three · Week 1, Week 2, Week 3, Week 4.</p></div><button className="btn" disabled={!filtered.length} onClick={printAll}>Print / PDF Register</button></div><div style={{display:'flex',gap:10,marginTop:12}}><div><label>Term</label><select value={termFilter} onChange={e=>setTermFilter(e.target.value)}><option value="all">All terms</option>{terms.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><div><label>Week</label><select value={weekFilter} onChange={e=>setWeekFilter(e.target.value)}><option value="all">All weeks</option>{[1,2,3,4].map(w=><option key={w} value={w}>Week {w}</option>)}</select></div></div><div style={{overflowX:'auto',marginTop:12}}><table className="prototype-table"><thead><tr><th>Requisition</th><th>Term</th><th>Week</th><th>Requested by</th><th>Item</th><th>Qty</th><th>Estimated</th><th>Action</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.requisition_no}</strong></td><td>{termName(r.term_id)}</td><td>Week {r.week_no}</td><td>{person(r.requested_by)}</td><td>{r.item_name}</td><td>{r.quantity}</td><td>{money(r.estimated_cost)}</td><td><button className="btn secondary" onClick={()=>printOne(r)}>Print</button></td></tr>)}{!filtered.length&&<tr><td colSpan={8} className="prototype-empty">No approved requisitions match the selected term and week.</td></tr>}</tbody></table></div></section></>}
 </div>}
