'use client'

import {useEffect,useMemo,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'

type RequestRow={id:string;staff_id:string;start_date:string;end_date:string;reason:string|null;status:string;request_type:string;approval_role:string;approved_by:string|null;decision_note:string|null;decided_at:string|null;start_time:string|null;end_time:string|null;pay_status:string|null;created_at:string}
type Staff={id:string;profile_id:string|null;first_name:string;middle_name:string|null;last_name:string;job_title:string|null;department:string|null}
type Details={applicationDate:string;absenceReason:string;absenceDetails:string;workCoverage:string;responsiblePerson:string;staffSignature:string}

const name=(s?:Staff)=>s?[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(' '):''
const typeLabel=(t:string)=>t==='short_leave'?'Short Leave':t==='off'?'Staff Off':'Leave'
const statusLabel=(s:string)=>s==='approved'?'APPROVED':s==='rejected'?'REJECTED':'PENDING'
const parseDetails=(raw:string|null):Details=>{try{const x=JSON.parse(raw||'');if(x&&typeof x==='object')return x as Details}catch{}return{applicationDate:'',absenceReason:'Other',absenceDetails:raw||'',workCoverage:'',responsiblePerson:'',staffSignature:''}}

export default function Page(){
 const db=createClient();
 const[staff,setStaff]=useState<Staff[]>([]);const[rows,setRows]=useState<RequestRow[]>([]);const[role,setRole]=useState('');const[userId,setUserId]=useState('');const[selected,setSelected]=useState<RequestRow|null>(null);const[msg,setMsg]=useState('');
 const[form,setForm]=useState({staff_id:'',request_type:'short_leave',applicationDate:new Date().toISOString().slice(0,10),absenceReason:'Personal',absenceDetails:'',start_date:'',end_date:'',start_time:'',end_time:'',workCoverage:'',responsiblePerson:'',staffSignature:'',pay_status:'paid'});
 const load=async()=>{const{data:{user}}=await db.auth.getUser();if(user){setUserId(user.id);const{data:p}=await db.from('profiles').select('role').eq('id',user.id).maybeSingle();setRole(p?.role||'')}const{data:st}=await db.from('staff').select('id,profile_id,first_name,middle_name,last_name,job_title,department').eq('status','active').order('first_name');setStaff(st||[]);const{data:r}=await db.from('leave_requests').select('id,staff_id,start_date,end_date,reason,status,request_type,approval_role,approved_by,decision_note,decided_at,start_time,end_time,pay_status,created_at').order('created_at',{ascending:false});setRows(r||[])};
 useEffect(()=>{load()},[]);
 const staffMap=useMemo(()=>Object.fromEntries(staff.map(s=>[s.id,s])),[staff]);
 const canApprove=['super_admin','headteacher','hr','hr_admin'].includes(role);const canSubmit=['super_admin','admin','headteacher','deputy_headteacher','class_teacher','subject_teacher','hr','hr_admin'].includes(role);
 const submit=async()=>{const st=staffMap[form.staff_id];if(!st){setMsg('Select the staff member.');return}if(!form.start_date||!form.end_date){setMsg('Select the absence dates.');return}if(form.request_type==='short_leave'&&!form.start_time){setMsg('Select the short-leave start time.');return}const details:Details={applicationDate:form.applicationDate,absenceReason:form.absenceReason,absenceDetails:form.absenceDetails,workCoverage:form.workCoverage,responsiblePerson:form.responsiblePerson,staffSignature:form.staffSignature};const{error}=await db.from('leave_requests').insert({staff_id:form.staff_id,start_date:form.start_date,end_date:form.end_date,start_time:form.request_type==='short_leave'?form.start_time:null,end_time:form.request_type==='short_leave'?form.end_time||null:null,reason:JSON.stringify(details),request_type:form.request_type,approval_role:form.request_type==='short_leave'?'headteacher':'hr',status:'pending',pay_status:form.pay_status});setMsg(error?.message||'Permission submitted for approval.');if(!error){setForm({...form,staff_id:'',absenceDetails:'',start_date:'',end_date:'',start_time:'',end_time:'',workCoverage:'',responsiblePerson:'',staffSignature:''});await load()}};
 const decide=async(id:string,status:'approved'|'rejected',pay?:'paid'|'unpaid')=>{const r=rows.find(x=>x.id===id);if(!r)return;const allowed=role==='super_admin'||(role==='headteacher'&&r.approval_role==='headteacher')||(['hr','hr_admin'].includes(role)&&r.approval_role==='hr');if(!allowed){setMsg('You do not have approval rights for this request.');return}const decisionDate=new Date().toISOString();const note=status==='approved'?`Approved as ${pay==='unpaid'?'Unpaid':'Paid'}.`:'Permission request rejected.';const{error}=await db.from('leave_requests').update({status,approved_by:userId,decided_at:decisionDate,decision_note:note,...(status==='approved'?{pay_status:pay}: {})}).eq('id',id).eq('status','pending');setMsg(error?.message||`${status==='approved'?'Approved':'Rejected'}.`);if(!error){setSelected({...r,status,approved_by:userId,decided_at:decisionDate,decision_note:note,pay_status:status==='approved'?(pay??r.pay_status):r.pay_status});await load()}};
 const print=()=>{if(!selected||selected.status==='pending')return;window.print()};
 const pending=rows.filter(r=>r.status==='pending');const history=rows.filter(r=>r.status!=='pending');
 return <main className="main">
  <div className="prototype-module no-print">
   <header className="prototype-module-header"><div><h1>Staff Permissions</h1><p>Submit leave/off requests, approve them and keep a permanent Leave / Off History with individual PDF / Print records.</p></div></header>
   <section className="prototype-kpis"><div className="prototype-kpi navy"><div className="prototype-kpi-icon">✎</div><div><div className="prototype-kpi-label">Applications</div><div className="prototype-kpi-value">{rows.length}</div></div></div><div className="prototype-kpi yellow"><div className="prototype-kpi-icon">!</div><div><div className="prototype-kpi-label">Pending</div><div className="prototype-kpi-value">{pending.length}</div></div></div><div className="prototype-kpi green"><div className="prototype-kpi-icon">✓</div><div><div className="prototype-kpi-label">Approved</div><div className="prototype-kpi-value">{history.filter(r=>r.status==='approved').length}</div></div></div><div className="prototype-kpi red"><div className="prototype-kpi-icon">×</div><div><div className="prototype-kpi-label">Rejected</div><div className="prototype-kpi-value">{history.filter(r=>r.status==='rejected').length}</div></div></div></section>
   {canSubmit&&<section className="card"><h2>New Staff Permission</h2><p className="muted">Short Leave goes to the Head Teacher. Staff Off goes to HR. Approval status and pay status are independent.</p><div className="form-grid">
    <select value={form.staff_id} onChange={e=>setForm({...form,staff_id:e.target.value})}><option value="">Select staff member</option>{staff.map(s=><option key={s.id} value={s.id}>{name(s)}</option>)}</select>
    <select value={form.request_type} onChange={e=>setForm({...form,request_type:e.target.value})}><option value="short_leave">Short Leave</option><option value="off">Staff Off</option></select>
    <input type="date" value={form.applicationDate} onChange={e=>setForm({...form,applicationDate:e.target.value})}/><select value={form.absenceReason} onChange={e=>setForm({...form,absenceReason:e.target.value})}><option>Personal</option><option>Medical</option><option>Official</option><option>Other</option></select>
    <input type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/><input type="date" value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/>
    {form.request_type==='short_leave'&&<><input type="time" value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})}/><input type="time" value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})}/></>}
    <select value={form.pay_status} onChange={e=>setForm({...form,pay_status:e.target.value})}><option value="paid">Paid</option><option value="unpaid">Unpaid</option></select>
    <textarea placeholder="Details of absence" value={form.absenceDetails} onChange={e=>setForm({...form,absenceDetails:e.target.value})}/><textarea placeholder="Arrangements for work coverage" value={form.workCoverage} onChange={e=>setForm({...form,workCoverage:e.target.value})}/><input placeholder="Person responsible for work" value={form.responsiblePerson} onChange={e=>setForm({...form,responsiblePerson:e.target.value})}/><input placeholder="Staff signature / name" value={form.staffSignature} onChange={e=>setForm({...form,staffSignature:e.target.value})}/>
   </div><button className="btn" style={{marginTop:12}} onClick={submit}>Submit Permission</button>{msg&&<p className="muted">{msg}</p>}</section>}
   <section className="card" style={{marginTop:16}}><h2>Pending Permissions</h2><div className="prototype-table-wrap"><table className="prototype-table"><thead><tr><th>STAFF</th><th>TYPE</th><th>FROM</th><th>TO</th><th>ROUTE</th><th>PAY</th><th>ACTION</th></tr></thead><tbody>{pending.map(r=><tr key={r.id}><td>{name(staffMap[r.staff_id])||'Staff member'}</td><td>{typeLabel(r.request_type)}</td><td>{r.start_date}{r.start_time?` ${r.start_time}`:''}</td><td>{r.end_date}{r.end_time?` ${r.end_time}`:''}</td><td>{r.approval_role==='headteacher'?'Head Teacher':'HR'}</td><td>{r.pay_status==='unpaid'?'Unpaid':'Paid'}</td><td>{canApprove&&<><button className="btn" onClick={()=>decide(r.id,'approved','paid')}>Approve Paid</button>{' '}<button className="btn" onClick={()=>decide(r.id,'approved','unpaid')}>Approve Unpaid</button>{' '}<button className="btn secondary" onClick={()=>decide(r.id,'rejected')}>Reject</button></>}<button className="btn secondary" onClick={()=>setSelected(r)} style={{marginLeft:6}}>View</button></td></tr>)}{!pending.length&&<tr><td colSpan={7} className="prototype-empty">No pending permissions.</td></tr>}</tbody></table></div></section>
   <section className="card history-card" style={{marginTop:16}}><div className="history-heading"><div><h2>Leave / Off History</h2><p className="muted">Every approved or rejected leave/off record stays here. Tap <strong>PDF / Print</strong> on that exact staff record to print only that permission sheet or save it as a PDF.</p></div></div><div className="prototype-table-wrap"><table className="prototype-table"><thead><tr><th>APPLICATION DATE</th><th>STAFF</th><th>TYPE</th><th>DURATION</th><th>STATUS</th><th>PAY</th><th>DECIDED</th><th>PDF / PRINT</th></tr></thead><tbody>{history.map(r=>{const d=parseDetails(r.reason);return <tr key={r.id}><td>{d.applicationDate||r.created_at.slice(0,10)}</td><td>{name(staffMap[r.staff_id])||'Staff member'}</td><td>{typeLabel(r.request_type)}</td><td>{r.start_date} → {r.end_date}</td><td><strong className={r.status==='approved'?'approved-text':'rejected-text'}>{statusLabel(r.status)}</strong></td><td>{r.pay_status==='unpaid'?'UNPAID':'PAID'}</td><td>{r.decided_at?r.decided_at.slice(0,10):'—'}</td><td><button className="btn pdf-btn" onClick={()=>setSelected(r)}>PDF / Print</button></td></tr>})}{!history.length&&<tr><td colSpan={8} className="prototype-empty">No leave/off history yet.</td></tr>}</tbody></table></div></section>
  </div>
  {selected&&<section className="permission-print-area"><div className="permission-paper"><div className="permission-school"><img src="/aic-cathedral-logo.svg" alt="AIC Cathedral"/><div><h1>AIC CATHEDRAL PRIMARY SCHOOL</h1><p>STAFF PERMISSION SHEET</p></div></div><div className={`permission-status ${selected.status==='approved'?'approved':selected.status==='rejected'?'rejected':'pending'}`}>{statusLabel(selected.status)}</div>{(()=>{const s=staffMap[selected.staff_id];const d=parseDetails(selected.reason);return <><div className="permission-grid"><div><b>Date of Application</b><span>{d.applicationDate||selected.created_at.slice(0,10)}</span></div><div><b>Staff Name</b><span>{name(s)||'—'}</span></div><div><b>Position</b><span>{s?.job_title||'—'}</span></div><div><b>Department</b><span>{s?.department||'—'}</span></div><div><b>Reason for Absence</b><span>{d.absenceReason||'—'}</span></div><div><b>Permission Type</b><span>{typeLabel(selected.request_type)}</span></div><div><b>Duration From</b><span>{selected.start_date}{selected.start_time?` ${selected.start_time}`:''}</span></div><div><b>Duration To</b><span>{selected.end_date}{selected.end_time?` ${selected.end_time}`:''}</span></div></div><div className="permission-block"><b>Details of Absence</b><p>{d.absenceDetails||'—'}</p></div><div className="permission-block"><b>Arrangements for Work Coverage</b><p>{d.workCoverage||'—'}</p></div><div className="permission-block"><b>Person Responsible for Work in My Absence</b><p>{d.responsiblePerson||'—'}</p></div><div className="permission-pay"><b>Pay Status</b><strong>{selected.status==='approved'?(selected.pay_status==='unpaid'?'UNPAID':'PAID'):'—'}</strong></div><div className="permission-official"><h3>Official Use Only</h3><div className="permission-grid"><div><b>Approval Status</b><span>{selected.status==='approved'?'Approved':selected.status==='rejected'?'Denied':'Pending'}</span></div><div><b>Date of Approval / Denial</b><span>{selected.decided_at?selected.decided_at.slice(0,10):'—'}</span></div><div><b>Approving Office</b><span>{selected.approval_role==='headteacher'?'Head Teacher / HOI':'HR'}</span></div><div><b>Comments</b><span>{selected.decision_note||'—'}</span></div></div></div><div className="permission-signatures"><div>Staff Signature<br/><strong>{d.staffSignature||'________________________'}</strong></div><div>Head Teacher / HR Signature<br/><strong>________________________</strong></div></div></>})()}<div className="no-print print-actions"><button className="btn" onClick={print}>Print / Save as PDF</button><button className="btn secondary" onClick={()=>setSelected(null)}>Close</button></div></div></section>}
  <style jsx>{`@media print{body *{visibility:hidden!important}.permission-print-area,.permission-print-area *{visibility:visible!important}.permission-print-area{position:absolute;left:0;top:0;width:100%;background:#fff}.permission-paper{box-shadow:none!important;border:0!important}.no-print{display:none!important}}.form-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.history-heading{display:flex;justify-content:space-between;gap:20px}.approved-text{color:#166534}.rejected-text{color:#991b1b}.pdf-btn{font-weight:800}.print-actions{display:flex;gap:8px;margin-top:18px}.permission-print-area{position:fixed;inset:0;background:rgba(15,23,42,.55);z-index:2000;overflow:auto;padding:30px}.permission-paper{max-width:850px;margin:auto;background:#fff;padding:38px;border-radius:14px;box-shadow:0 20px 60px rgba(0,0,0,.25);font-family:Arial,sans-serif;color:#172033}.permission-school{display:flex;align-items:center;gap:18px;border-bottom:3px solid #7b1e2b;padding-bottom:18px}.permission-school img{width:72px;height:72px;object-fit:contain}.permission-school h1{margin:0;font-size:22px}.permission-school p{margin:5px 0 0;font-weight:800;letter-spacing:2px}.permission-status{text-align:center;font-size:26px;font-weight:900;letter-spacing:3px;border:3px solid;padding:12px;margin:22px 0}.permission-status.approved{color:#166534;border-color:#166534}.permission-status.rejected{color:#991b1b;border-color:#991b1b}.permission-status.pending{color:#92400e;border-color:#92400e}.permission-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin:18px 0}.permission-grid div{border:1px solid #d7dce5;padding:10px}.permission-grid b,.permission-block b{display:block;font-size:12px;text-transform:uppercase;color:#596273;margin-bottom:5px}.permission-grid span{display:block;font-weight:700}.permission-block{border:1px solid #d7dce5;padding:12px;margin:12px 0;min-height:60px}.permission-block p{margin:0;white-space:pre-wrap}.permission-pay{display:flex;justify-content:space-between;border:2px solid #7b1e2b;padding:12px;margin:16px 0}.permission-official{border:2px solid #172033;padding:16px;margin-top:20px}.permission-official h3{margin:0 0 10px}.permission-signatures{display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-top:35px;font-size:13px}@media(max-width:700px){.permission-grid,.permission-signatures{grid-template-columns:1fr}.permission-print-area{padding:10px}.permission-paper{padding:20px}.permission-school h1{font-size:17px}}`}</style>
 </main>
}
