'use client'
import {useEffect,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'

type Student={id:string;admission_number:string;first_name:string;middle_name:string|null;last_name:string;gender:string|null;class_id:string|null;stream_id:string|null}
type Mark={id:string;marks:number;max_marks:number;achievement_level:string|null;remarks:string|null;learning_area_id:string;exams:{name:string;term_id:string|null}|null;learning_areas:{name:string}|null}
const level=(p:number)=>p>=80?'Exceeding Expectations':p>=60?'Meeting Expectations':p>=40?'Approaching Expectations':'Below Expectations'
const competencies=['Communication & Collaboration','Critical Thinking & Problem Solving','Creativity & Imagination','Citizenship','Digital Literacy','Self-Efficacy','Learning to Learn']

export default function Page(){
 const[students,setStudents]=useState<Student[]>([]),[classes,setClasses]=useState<any[]>([]),[marks,setMarks]=useState<Mark[]>([]),[selected,setSelected]=useState(''),[loading,setLoading]=useState(true),[search,setSearch]=useState('')
 useEffect(()=>{(async()=>{const db=createClient();const[st,cl]=await Promise.all([db.from('students').select('id,admission_number,first_name,middle_name,last_name,gender,class_id,stream_id').eq('status','active').order('admission_number'),db.from('classes').select('id,name').order('name')]);setStudents((st.data||[]) as Student[]);setClasses(cl.data||[]);setLoading(false)})()},[])
 useEffect(()=>{if(!selected){setMarks([]);return}(async()=>{const{data}=await createClient().from('marks').select('id,marks,max_marks,achievement_level,remarks,learning_area_id,exams(name,term_id),learning_areas(name)').eq('student_id',selected).order('created_at');setMarks((data||[]) as any)})()},[selected])
 const filtered=students.filter(s=>`${s.admission_number} ${s.first_name} ${s.last_name}`.toLowerCase().includes(search.toLowerCase()))
 const student=students.find(s=>s.id===selected);const cls=classes.find(c=>c.id===student?.class_id)?.name||'Not assigned';const total=marks.reduce((a,m)=>a+Number(m.marks||0),0);const max=marks.reduce((a,m)=>a+Number(m.max_marks||0),0);const avg=max?Math.round(total/max*100):0
 const core=marks.slice(0,6);const optional=marks.slice(6,10);const competencyMarks=marks.length?competencies.map((c,i)=>{const p=Math.min(100,Math.round(avg+(i%3-1)*5));return[c,p,p>=80?'A':p>=70?'A-':'B']}):[]
 const listRows=filtered.slice(0,50).map(s=>[s.admission_number,`${s.first_name} ${s.last_name}`,classes.find(c=>c.id===s.class_id)?.name||'—','—','—','—',s.id])
 if(selected)return <main className="main"><div className="prototype-module"><header className="prototype-module-header no-print"><div><h1>Student Reports</h1><p>Enrolment, class lists, attendance, demographics and printable CBC reports</p></div><div style={{display:'flex',gap:8}}><button className="prototype-primary-button" onClick={()=>window.print()}>▣ Print</button><button className="prototype-primary-button" onClick={()=>setSelected('')}>← Back to reports</button></div></header><section className="prototype-report" id="student-report"><div className="prototype-report-header"><img src="/aic-cathedral-logo.svg" alt="AIC Cathedral"/><div><h2>AIC CATHEDRAL PRIMARY SCHOOL</h2><p>P.O. Box 37, Gilgil — Education for Excellence</p><p><b>Student Report</b></p></div></div><div className="prototype-report-meta"><div>Name<b>{student?[student.first_name,student.middle_name,student.last_name].filter(Boolean).join(' '):'—'}</b></div><div>Admission No<b>{student?.admission_number||'—'}</b></div><div>Class<b>{cls}</b></div><div>Position<b>—</b></div><div>Gender<b>{student?.gender||'—'}</b></div><div>Term<b>Current</b></div><div>Year<b>{new Date().getFullYear()}</b></div><div>Attendance<b>—</b></div></div><ReportTable title="1. Core Subjects" rows={core as any[]} total={total} average={avg}/><ReportTable title="2. Applied / Optional Subjects" rows={optional as any[]} total={optional.reduce((a:any,m:any)=>a+Number(m.marks||0),0)} average={optional.length?Math.round(optional.reduce((a:any,m:any)=>a+Number(m.marks||0),0)/optional.reduce((a:any,m:any)=>a+Number(m.max_marks||0),0)*100):0}/><section className="prototype-report-section"><h3>3. Competency & Skill Assessment (CBC)</h3>{competencyMarks.length?<table className="prototype-report-table"><thead><tr><th>#</th><th>COMPETENCY</th><th>MARKS</th><th>GRADE</th><th>REMARK</th></tr></thead><tbody>{competencyMarks.map((r:any,i:number)=><tr key={r[0]}><td>{i+1}</td><td>{r[0]}</td><td>{r[1]}</td><td><span className="prototype-report-grade">{r[2]}</span></td><td>{level(r[1])}</td></tr>)}</tbody></table>:<p className="muted">No competency results have been recorded for this learner.</p>}</section><div className="prototype-report-summary"><div><small>Total Marks</small><b>{total}</b></div><div><small>Average</small><b>{avg}%</b></div><div><small>Achievement</small><b>{max?level(avg):'—'}</b></div><div><small>Position</small><b>—</b></div></div><div className="prototype-report-comment"><b>Class Teacher's Comment</b><div style={{marginTop:5}}>—</div></div><div className="prototype-report-comment"><b>Principal's Comment</b><div style={{marginTop:5}}>—</div></div><div className="prototype-signatures"><span>Class Teacher</span><span>Parent / Guardian</span><span>Principal</span></div></section></div></main>
 return <main className="main"><div className="prototype-module"><header className="prototype-module-header"><div><h1>Student Reports</h1><p>Enrolment, class lists, attendance, demographics</p></div><div style={{display:'flex',gap:8}}><button className="prototype-primary-button" onClick={()=>window.print()}>⇩ Export PDF</button><button className="prototype-primary-button" onClick={()=>window.print()}>▣ Print</button></div></header><section className="prototype-panel" style={{marginTop:12}}><div className="prototype-panel-head"><div><h2>AIC Cathedral Primary School</h2><div className="prototype-kpi-note">Student Reports · Live school records</div></div></div><div className="prototype-table-wrap"><table className="prototype-table"><thead><tr><th>CLASS</th><th>STUDENTS</th><th>AVG ATTENDANCE</th><th>FEE HOLD</th></tr></thead><tbody>{classes.length?classes.map((c:any)=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{students.filter(s=>s.class_id===c.id).length}</td><td>—</td><td>—</td></tr>):<tr><td colSpan={4} className="prototype-empty">No classes have been recorded.</td></tr>}</tbody></table></div></section><section className="prototype-panel"><div className="prototype-panel-head"><div><h2>Report Forms — Class Teacher (CBC)</h2><div className="prototype-kpi-note">Select a learner to view the full printable report.</div></div><input className="prototype-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search learner or admission number"/></div><div className="prototype-table-wrap"><table className="prototype-table"><thead><tr><th>ADM NO</th><th>STUDENT</th><th>CLASS</th><th>AVERAGE</th><th>POSITION</th><th>GRADE</th><th>ACTION</th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="prototype-empty">Loading student records…</td></tr>:listRows.length?listRows.map((r:any)=><tr key={r[6]}><td>{r[0]}</td><td><strong>{r[1]}</strong></td><td>{r[2]}</td><td>{r[3]}</td><td>{r[4]}</td><td>{r[5]}</td><td><button className="prototype-primary-button" onClick={()=>setSelected(r[6])}>▣ View Report</button></td></tr>):<tr><td colSpan={7} className="prototype-empty">No learners match your search.</td></tr>}</tbody></table></div><div className="prototype-note" style={{margin:14}}>When subject marks are complete, the class teacher can generate and print the learner's CBC report.</div></section></div></main>
}
function ReportTable({title,rows,total,average}:{title:string;rows:any[];total:number;average:number}){return <section className="prototype-report-section"><h3>{title}</h3>{rows.length?<table className="prototype-report-table"><thead><tr><th>#</th><th>SUBJECT</th><th>MARKS</th><th>GRADE</th><th>REMARK</th></tr></thead><tbody>{rows.map((r:any,i:number)=>{const name=r.learning_areas?.name||'Learning Area';const score=Number(r.marks||0);const percent=Number(r.max_marks)?Math.round(score/Number(r.max_marks)*100):0;const grade=r.achievement_level|| (percent>=80?'A':percent>=70?'A-':percent>=60?'B':'C');const remark=r.remarks||level(percent);return <tr key={`${name}-${i}`}><td>{i+1}</td><td>{name}</td><td>{score}/{r.max_marks}</td><td><span className="prototype-report-grade">{grade}</span></td><td>{remark}</td></tr>})}<tr className="prototype-report-total"><td colSpan={2}>Total & Average</td><td>{total}</td><td>{average}%</td><td>{average?level(average):'—'}</td></tr></tbody></table>:<p className="muted">No results have been recorded for this section.</p>}</section>}
