'use client'
import {useMemo,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'

type BudgetRow={id:string;category:string;section:'income'|'expenditure';budget:number;actual:number;notes:string|null}
type Props={rows:BudgetRow[]}
const income=['Fees Income','Fees Discounts','Interview Fees','Admission Fees']
const expenditure=['Salaries','Supplier Invoices']
const money=(n:number)=>`KES ${Number(n||0).toLocaleString('en-KE')}`
export default function Budget({rows:initial}:Props){
 const [rows,setRows]=useState(initial),[section,setSection]=useState<'income'|'expenditure'>('income'),[category,setCategory]=useState('Fees Income'),[budget,setBudget]=useState(''),[notes,setNotes]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 const categories=section==='income'?income:expenditure
 const incomeRows=useMemo(()=>rows.filter(r=>r.section==='income'),[rows]),expenseRows=useMemo(()=>rows.filter(r=>r.section==='expenditure'),[rows])
 const totalIncome=incomeRows.reduce((n,r)=>n+r.budget,0),actualIncome=incomeRows.reduce((n,r)=>n+r.actual,0)
 const totalExpense=expenseRows.reduce((n,r)=>n+r.budget,0),actualExpense=expenseRows.reduce((n,r)=>n+r.actual,0)
 const add=async()=>{const amount=Number(budget);if(!amount){setMessage('Enter a budget amount.');return}setSaving(true);setMessage('');const db=createClient();const{data,error}=await db.from('budget_lines').insert({category,section,budget_amount:amount,notes:notes||null}).select('id,category,section,budget_amount,actual_amount,notes').single();if(error){setMessage(error.message);setSaving(false);return}setRows(x=>[...x,{id:data.id,category:data.category,section:data.section,budget:Number(data.budget_amount||0),actual:Number(data.actual_amount||0),notes:data.notes}]);setBudget('');setNotes('');setMessage('Budget line added successfully.');setSaving(false)}
 return <section className="card" style={{marginBottom:16}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><h2 style={{marginBottom:4}}>Budget & Financial Planning</h2><p className="muted">Plan proposed income and expenditure, then compare budgeted figures with actual financial activity.</p></div></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:10,margin:'16px 0'}}><div style={{padding:14,background:'#f5f8fc',borderRadius:10}}><small>Proposed Income</small><strong style={{display:'block'}}>{money(totalIncome)}</strong><span className="muted">Actual: {money(actualIncome)}</span></div><div style={{padding:14,background:'#f5f8fc',borderRadius:10}}><small>Expenditure Budget</small><strong style={{display:'block'}}>{money(totalExpense)}</strong><span className="muted">Actual: {money(actualExpense)}</span></div><div style={{padding:14,background:'#f5f8fc',borderRadius:10}}><small>Projected Surplus</small><strong style={{display:'block'}}>{money(totalIncome-totalExpense)}</strong></div><div style={{padding:14,background:(actualIncome-actualExpense)>=0?'#effaf3':'#fff5f5',borderRadius:10}}><small>Actual Surplus / (Deficit)</small><strong style={{display:'block'}}>{money(actualIncome-actualExpense)}</strong></div></div>
 <div style={{display:'flex',gap:8,marginBottom:14,flexWrap:'wrap'}}><button type="button" className="btn" onClick={()=>setSection('income')} disabled={section==='income'}>Proposed Income</button><button type="button" className="btn" onClick={()=>setSection('expenditure')} disabled={section==='expenditure'}>Expenditure</button></div>
 <div style={{border:'1px solid #e2e8f0',borderRadius:10,padding:14,marginBottom:16}}><h3 style={{marginTop:0}}>Add {section==='income'?'income':'expenditure'} budget</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8}}><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select><input type="number" min="0" value={budget} onChange={e=>setBudget(e.target.value)} placeholder="Budget amount (KES)"/><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Notes / assumptions"/><button className="btn" type="button" onClick={add} disabled={saving}>{saving?'Saving…':'Add Budget Line'}</button></div>{message&&<p style={{fontSize:13,color:message.includes('successfully')?'#18794e':'#b42318'}}>{message}</p>}</div>
 <div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={{textAlign:'left',padding:10}}>Category</th><th style={{textAlign:'right',padding:10}}>Budget</th><th style={{textAlign:'right',padding:10}}>Actual</th><th style={{textAlign:'right',padding:10}}>Variance</th><th style={{textAlign:'left',padding:10}}>Notes</th></tr></thead><tbody>{rows.filter(r=>r.section===section).map(r=><tr key={r.id}><td style={{padding:10,borderTop:'1px solid #edf0f4'}}>{r.category}</td><td style={{padding:10,textAlign:'right',borderTop:'1px solid #edf0f4'}}>{money(r.budget)}</td><td style={{padding:10,textAlign:'right',borderTop:'1px solid #edf0f4'}}>{money(r.actual)}</td><td style={{padding:10,textAlign:'right',borderTop:'1px solid #edf0f4'}}>{money(r.budget-r.actual)}</td><td style={{padding:10,borderTop:'1px solid #edf0f4'}}>{r.notes||'—'}</td></tr>)}{rows.filter(r=>r.section===section).length===0&&<tr><td colSpan={5} className="muted" style={{padding:16}}>No budget lines added yet.</td></tr>}</tbody></table></div></section>
}
