'use client'
import {useEffect,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'

type Tx={id:string;transaction_type:'income'|'expense';category:string;description:string|null;amount:number;reference_no:string|null;transaction_date:string}
const money=(n:number)=>`KES ${Number(n||0).toLocaleString('en-KE')}`
export default function Cashbook(){
 const [rows,setRows]=useState<Tx[]>([]),[form,setForm]=useState({transaction_type:'income',category:'Other income',description:'',amount:'',reference_no:'',transaction_date:new Date().toISOString().slice(0,10)}),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
 const load=async()=>{const{data,error}=await createClient().from('finance_transactions').select('*').order('transaction_date',{ascending:false}).order('created_at',{ascending:false});if(error)setMessage(error.message);else setRows((data||[]) as Tx[])}
 useEffect(()=>{void load()},[])
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!form.amount||!form.category)return;setSaving(true);const{error}=await createClient().from('finance_transactions').insert({...form,amount:Number(form.amount)});setMessage(error?.message||'Transaction recorded successfully.');setSaving(false);if(!error){setForm({...form,amount:'',description:'',reference_no:''});await load()}}
 const totalIn=rows.filter(x=>x.transaction_type==='income').reduce((n,x)=>n+Number(x.amount),0),totalOut=rows.filter(x=>x.transaction_type==='expense').reduce((n,x)=>n+Number(x.amount),0)
 const exportPdf=()=>{const w=window.open('','_blank','width=1100,height=900');if(!w)return;const body=rows.map(x=>`<tr><td>${x.transaction_date}</td><td>${x.transaction_type.toUpperCase()}</td><td>${x.category}</td><td>${x.description||'—'}</td><td>${money(x.amount)}</td><td>${x.reference_no||'—'}</td></tr>`).join('');w.document.write(`<!doctype html><html><head><title>AIC Cathedral Cashbook</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#172033}header{display:flex;align-items:center;gap:16px;border-bottom:4px solid #b8860b;padding-bottom:14px}header img{width:64px;height:64px;object-fit:contain}h1{margin:0;color:#12385d}table{width:100%;border-collapse:collapse;margin-top:22px}th,td{padding:9px;border:1px solid #d8dee8;text-align:left}th{background:#12385d;color:#fff}.totals{display:flex;gap:20px;margin-top:18px}.box{padding:12px 18px;border-radius:10px;background:#f5f8fc}@media print{body{padding:8mm}}</style></head><body><header><img src="${location.origin}/aic-cathedral-logo.svg"><div><h1>AIC CATHEDRAL PRIMARY SCHOOL</h1><div>Official Finance Cashbook</div></div></header><div class="totals"><div class="box"><b>Money in</b><br>${money(totalIn)}</div><div class="box"><b>Money out</b><br>${money(totalOut)}</div><div class="box"><b>Net</b><br>${money(totalIn-totalOut)}</div></div><table><thead><tr><th>Date</th><th>Type</th><th>Category</th><th>Description</th><th>Amount</th><th>Reference</th></tr></thead><tbody>${body}</tbody></table><script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body></html>`);w.document.close()}
 return <section className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h2 style={{margin:0}}>Money in & money out</h2><p className="muted" style={{margin:'5px 0 0'}}>Record school income and expenses in one cashbook for complete financial analysis.</p></div><button className="btn secondary" onClick={exportPdf}>Export cashbook PDF</button></div><div className="cards" style={{marginTop:16}}><div className="card"><div className="muted">Money in</div><div className="number">{money(totalIn)}</div></div><div className="card"><div className="muted">Money out</div><div className="number">{money(totalOut)}</div></div><div className="card"><div className="muted">Net cash movement</div><div className="number">{money(totalIn-totalOut)}</div></div></div><form onSubmit={save} style={{display:'grid',gridTemplateColumns:'1fr 1.2fr 1.4fr 1fr 1fr auto',gap:8,marginTop:18}}><select value={form.transaction_type} onChange={e=>setForm({...form,transaction_type:e.target.value as 'income'|'expense'})}><option value="income">Money in</option><option value="expense">Money out</option></select><input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Category" required/><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description"/><input type="number" min="0" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="Amount (KES)" required/><input type="date" value={form.transaction_date} onChange={e=>setForm({...form,transaction_date:e.target.value})}/><button className="btn" disabled={saving}>{saving?'Saving…':'Add transaction'}</button></form>{message&&<p className="muted">{message}</p>}<div style={{overflowX:'auto',marginTop:18}}><table className="prototype-table"><thead><tr><th>Date</th><th>Type</th><th>Category</th><th>Description</th><th>Amount</th><th>Reference</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td>{x.transaction_date}</td><td>{x.transaction_type==='income'?'Money in':'Money out'}</td><td>{x.category}</td><td>{x.description||'—'}</td><td>{money(x.amount)}</td><td>{x.reference_no||'—'}</td></tr>):<tr><td colSpan={6} className="prototype-empty">No cashbook transactions yet.</td></tr>}</tbody></table></div></section>
}
