'use client'
import {useEffect,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'

type Row={id:string;admission_number:string;name:string;due:number;paid:number;status:string;hold:boolean;bus:string;driver:string}

export default function FeeHoldManager({students,accounts}:{students:any[];accounts:any[]}){
 const db=createClient();const[rows,setRows]=useState<Row[]>([]);const[busy,setBusy]=useState('');const[message,setMessage]=useState('')
 const load=async()=>{const ids=students.map(s=>s.id);if(!ids.length){setRows([]);return}const[{data:feeData,error:feeError},{data:assignments,error:assignmentError},{data:routes}]=await Promise.all([
   db.from('transport_fee_status').select('student_id,cleared').in('student_id',ids),
   db.from('transport_assignments').select('student_id,route_id').in('student_id',ids),
   db.from('transport_routes').select('id,vehicle_no,driver_name,route_name')
 ]);if(feeError){setMessage(feeError.message);return}if(assignmentError){setMessage(assignmentError.message);return}
 const hm=new Map((feeData||[]).map(x=>[x.student_id,!x.cleared]));const routeMap=new Map((routes||[]).map(x=>[x.id,x]));const assignmentMap=new Map((assignments||[]).map(x=>[x.student_id,routeMap.get(x.route_id)]));
 setRows(students.map(s=>{const a=accounts.find(x=>x.student_id===s.id);const route=assignmentMap.get(s.id);return{id:s.id,admission_number:s.admission_number,name:[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(' '),due:Number(a?.amount_due||0),paid:Number(a?.amount_paid||0),status:String(a?.status||'unpaid'),hold:hm.get(s.id)||false,bus:String(route?.vehicle_no||'—'),driver:String(route?.driver_name||'—')}}))}
 useEffect(()=>{void load();const channel=db.channel('transport-fee-status-live').on('postgres_changes',{event:'*',schema:'public',table:'transport_fee_status'},()=>void load()).subscribe();return()=>{void db.removeChannel(channel)}},[])
 const toggle=async(r:Row)=>{setBusy(r.id);setMessage('');const{data:as}=await db.from('transport_assignments').select('route_id').eq('student_id',r.id).limit(1);const routeId=as?.[0]?.route_id||null;const{data:user}=await db.auth.getUser();const applyingHold=!r.hold;const{error}=await db.from('transport_fee_status').upsert({student_id:r.id,route_id:routeId,cleared:r.hold,marked_by:user.user?.id||null,marked_at:new Date().toISOString()},{onConflict:'student_id'});if(error){setBusy('');setMessage(error.message);return}
  const{data:links,error:parentError}=await db.from('student_parents').select('parent_id').eq('student_id',r.id);let notified=0;let notifyProblem=''
  if(!parentError&&links?.length){const title=applyingHold?'Fee Hold Notice':'Fee Hold Cleared';const body=applyingHold?`Finance has placed ${r.name} on fee hold. Please contact the school finance office and clear the outstanding school fees. The learner's transport status is currently on hold.`:`The fee hold for ${r.name} has been cleared by Finance. The learner's transport status has been restored.`;const{error:notifyError}=await db.from('parent_notifications').insert(links.map(x=>({parent_id:x.parent_id,student_id:r.id,title,body,type:'fee_hold'})));if(!notifyError)notified=links.length;else notifyProblem=notifyError.message}else if(parentError)notifyProblem=parentError.message
  setBusy('');setMessage(notifyProblem?`Fee status updated, but parent notification could not be sent: ${notifyProblem}`:`${r.name}: ${applyingHold?'fee hold applied':'fee hold cleared'}. ${notified?`Notification sent to ${notified} parent/guardian${notified===1?'':'s'}.`:'No linked parent/guardian was found to notify.'}`);await load()}
 return <section className="prototype-panel"><div className="prototype-panel-head"><div><h2>Transport Fee Hold & Parent Notification</h2><p>Apply or clear a fee hold. Bus and driver details are shown automatically from the learner's transport assignment.</p></div><button type="button" className="prototype-secondary-button" onClick={()=>window.print()}>Print Fee Hold List</button></div>{message&&<div className="prototype-note">{message}</div>}<div className="prototype-panel-body"><div className="prototype-table-wrap"><table className="prototype-table"><thead><tr><th>STUDENT</th><th>ADMISSION NO.</th><th>BUS</th><th>DRIVER</th><th>FEES DUE</th><th>PAID</th><th>BALANCE</th><th>FEE STATUS</th><th>TRANSPORT</th><th>ACTION</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.admission_number}</td><td>{r.bus}</td><td>{r.driver}</td><td>KES {r.due.toLocaleString('en-KE')}</td><td>KES {r.paid.toLocaleString('en-KE')}</td><td>KES {Math.max(r.due-r.paid,0).toLocaleString('en-KE')}</td><td>{r.status}</td><td>{r.hold?'X — HOLD':'✓ — CLEARED'}</td><td><button type="button" className={r.hold?'prototype-primary-button':'prototype-secondary-button'} disabled={busy===r.id} onClick={()=>void toggle(r)}>{busy===r.id?'Saving…':r.hold?'Clear Fee Hold':'Put on Fee Hold'}</button></td></tr>)}{!rows.length&&<tr><td colSpan={10} className="prototype-empty">No active learners.</td></tr>}</tbody></table></div></div></section>
}
