'use client'
import {useEffect,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'

type Row={id:string;admission_number:string;name:string;due:number;paid:number;status:string;hold:boolean}

export default function FeeHoldManager({students,accounts}:{students:any[];accounts:any[]}){
 const db=createClient();const[rows,setRows]=useState<Row[]>([]);const[busy,setBusy]=useState('');const[message,setMessage]=useState('')
 const load=async()=>{const ids=students.map(s=>s.id);if(!ids.length){setRows([]);return}const{data}=await db.from('transport_fee_status').select('student_id,cleared').in('student_id',ids);const hm=new Map((data||[]).map(x=>[x.student_id,!x.cleared]));setRows(students.map(s=>{const a=accounts.find(x=>x.student_id===s.id);return{id:s.id,admission_number:s.admission_number,name:[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(' '),due:Number(a?.amount_due||0),paid:Number(a?.amount_paid||0),status:String(a?.status||'unpaid'),hold:hm.get(s.id)||false}}))}
 useEffect(()=>{void load()},[])
 const toggle=async(r:Row)=>{setBusy(r.id);setMessage('');const{data:as}=await db.from('transport_assignments').select('route_id').eq('student_id',r.id).limit(1);const routeId=as?.[0]?.route_id||null;const{error}=await db.from('transport_fee_status').upsert({student_id:r.id,route_id:routeId,cleared:r.hold,marked_at:new Date().toISOString()},{onConflict:'student_id'});setBusy('');if(error)setMessage(error.message);else{setMessage(`${r.name}: ${r.hold?'fee hold cleared':'fee hold applied'}. Transport will see the change automatically.`);await load()}}
 return <section className="prototype-panel"><div className="prototype-panel-head"><div><h2>Transport Fee Hold</h2><p>Use this button when a learner's transport/fee payment should stop or allow boarding. The status is shared with Transport automatically.</p></div><button className="prototype-secondary-button" onClick={()=>window.print()}>Print Fee Hold List</button></div>{message&&<div className="prototype-note">{message}</div>}<div className="prototype-panel-body"><div className="prototype-table-wrap"><table className="prototype-table"><thead><tr><th>STUDENT</th><th>ADMISSION NO.</th><th>FEES DUE</th><th>PAID</th><th>BALANCE</th><th>FEE STATUS</th><th>TRANSPORT</th><th>ACTION</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.admission_number}</td><td>KES {r.due.toLocaleString('en-KE')}</td><td>KES {r.paid.toLocaleString('en-KE')}</td><td>KES {Math.max(r.due-r.paid,0).toLocaleString('en-KE')}</td><td>{r.status}</td><td>{r.hold?'X — HOLD':'✓ — CLEARED'}</td><td><button className={r.hold?'prototype-primary-button':'prototype-secondary-button'} disabled={busy===r.id} onClick={()=>void toggle(r)}>{busy===r.id?'Saving…':r.hold?'Clear Fee Hold':'Put on Fee Hold'}</button></td></tr>)}{!rows.length&&<tr><td colSpan={8} className="prototype-empty">No active learners.</td></tr>}</tbody></table></div></div></section>
}
