'use client'
import {useMemo,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'
type Student={id:string;admission_number:string;first_name:string;middle_name?:string|null;last_name:string;class_id:string|null;stream_id:string|null;class_name:string;stream_name:string}
type Receipt={receipt_no:string;amount_paid:number;balance:number;payment_method:string;reference_no:string|null;paid_at:string}
type Props={students:Student[]}
const otherOptions=['Graduation','Interview','Admission'] as const
const otherFee:Record<string,number>={Graduation:1500,Interview:500,Admission:1000}
export default function FinanceDesk({students}:Props){
 const [query,setQuery]=useState(''),[classFilter,setClassFilter]=useState(''),[streamFilter,setStreamFilter]=useState(''),[selected,setSelected]=useState<Student|null>(null)
 const [due,setDue]=useState(''),[payment,setPayment]=useState(''),[paymentType,setPaymentType]=useState('school_fees'),[otherType,setOtherType]=useState('Admission'),[method,setMethod]=useState('mpesa'),[reference,setReference]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[receipt,setReceipt]=useState<Receipt|null>(null)
 const classes=useMemo(()=>Array.from(new Set(students.map(s=>s.class_name).filter(Boolean))),[students])
 const filtered=useMemo(()=>students.filter(s=>{const q=query.trim().toLowerCase();const full=`${s.first_name} ${s.middle_name||''} ${s.last_name}`.toLowerCase();return(!q||s.admission_number.toLowerCase().includes(q)||full.includes(q))&&(!classFilter||s.class_name===classFilter)&&(!streamFilter||s.stream_name===streamFilter)}),[students,query,classFilter,streamFilter])
 const grouped=useMemo(()=>filtered.reduce<Record<string,Student[]>>((a,s)=>{const key=`${s.class_name} — ${s.stream_name}`;(a[key]??=[]).push(s);return a},{}),[filtered])
 const choose=(s:Student)=>{setSelected(s);setMessage('');setDue('');setPayment('');setReference('');setReceipt(null);setPaymentType('school_fees');setOtherType('Admission')}
 const saveAccount=async()=>{if(!selected)return;setSaving(true);setMessage('');const db=createClient();const{data:term}=await db.from('terms').select('id,name').eq('is_current',true).eq('status','active').order('start_date',{ascending:false}).limit(1).maybeSingle();const{data:year}=await db.from('academic_years').select('id').eq('is_current',true).eq('status','active').order('year',{ascending:false}).limit(1).maybeSingle();const termFee=Number(due);if(!termFee){setMessage('Enter the termly fee amount.');setSaving(false);return}const{error}=await db.from('fee_accounts').insert({student_id:selected.id,academic_year_id:year?.id||null,term_id:term?.id||null,amount_due:termFee,amount_paid:0,status:'unpaid',charge_type:'term_fee',charge_label:'Termly school fees'});setMessage(error?error.message:'Termly fee account saved successfully.');setSaving(false)}
 const savePayment=async()=>{if(!selected||!payment)return;setSaving(true);setMessage('');setReceipt(null);const db=createClient();let accountId:string|null=null;let category='school_fees';let label='School fees';let amountDue=0;
 if(paymentType==='school_fees'){const{data:term}=await db.from('terms').select('id,name').eq('is_current',true).eq('status','active').order('start_date',{ascending:false}).limit(1).maybeSingle();const{data:year}=await db.from('academic_years').select('id').eq('is_current',true).eq('status','active').order('year',{ascending:false}).limit(1).maybeSingle();const{data:existing}=await db.from('fee_accounts').select('id,amount_due,amount_paid').eq('student_id',selected.id).eq('charge_type','term_fee').eq('term_id',term?.id||'').order('created_at',{ascending:false}).limit(1).maybeSingle();if(existing?.id)accountId=existing.id;else{amountDue=Number(due)||0;if(!amountDue){const{data:fee}=await db.rpc('school_term_fee',{p_class_name:selected.class_name});amountDue=Number(fee||0)}if(!amountDue){setMessage('No fee structure was found for this class.');setSaving(false);return}const created=await db.from('fee_accounts').insert({student_id:selected.id,academic_year_id:year?.id||null,term_id:term?.id||null,amount_due:amountDue,amount_paid:0,status:'unpaid',charge_type:'term_fee',charge_label:'Termly school fees'}).select('id').single();if(created.error||!created.data?.id){setMessage(created.error?.message||'Fee account could not be created.');setSaving(false);return}accountId=created.data.id}}
 else{category=otherType.toLowerCase();label=`${otherType} Fee`;amountDue=otherFee[otherType];const{data:term}=await db.from('terms').select('id,name').eq('is_current',true).eq('status','active').order('start_date',{ascending:false}).limit(1).maybeSingle();const{data:year}=await db.from('academic_years').select('id').eq('is_current',true).eq('status','active').order('year',{ascending:false}).limit(1).maybeSingle();const termNumber=Number(String(term?.name||'').match(/\d+/)?.[0]||0);if(otherType==='Graduation'&&selected.class_name!=='PP2'){setMessage('Graduation Fee is only for PP2.');setSaving(false);return}if(otherType==='Interview'&&!/^Grade [1-9]$/.test(selected.class_name)){setMessage('Interview Fee is for Grades 1–9 new learners.');setSaving(false);return}if(otherType==='Graduation'&&termNumber!==3){setMessage('Graduation Fee is payable in 3rd Term.');setSaving(false);return}const created=await db.from('fee_accounts').insert({student_id:selected.id,academic_year_id:year?.id||null,term_id:term?.id||null,amount_due:amountDue,amount_paid:0,status:'unpaid',charge_type:category,charge_label:label}).select('id').single();if(created.error||!created.data?.id){setMessage(created.error?.message||'Other fee account could not be created.');setSaving(false);return}accountId=created.data.id}
 const{data:paymentRow,error}=await db.from('fee_payments').insert({student_id:selected.id,fee_account_id:accountId,amount:Number(payment),payment_method:method,reference_no:reference||null,payment_category:category}).select('id').single();if(error||!paymentRow){setMessage(error?.message||'Payment could not be recorded.');setSaving(false);return}
 const{data:r}=await db.from('fee_receipts').select('receipt_no,amount_paid,balance,payment_method,reference_no,paid_at').eq('payment_id',paymentRow.id).single();setReceipt(r as Receipt|null);setMessage(r?'Payment recorded and receipt generated automatically.':'Payment recorded successfully.');setPayment('');setReference('');setSaving(false)}
 const printReceipt=()=>{if(typeof window!=='undefined')window.print()}
 return <section className="card" style={{marginBottom:16}}><div style={{marginBottom:16}}><h2 style={{marginBottom:4}}>Fee collection desk</h2><p className="muted">The school fee structure is applied automatically by class. Record the amount paid and the system calculates the outstanding balance.</p></div>
  <div style={{display:'grid',gridTemplateColumns:'minmax(220px,2fr) repeat(2,minmax(150px,1fr))',gap:10,marginBottom:18}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search admission number or student name"/><select value={classFilter} onChange={e=>setClassFilter(e.target.value)}><option value="">All grades/classes</option>{classes.map(c=><option key={c}>{c}</option>)}</select><select value={streamFilter} onChange={e=>setStreamFilter(e.target.value)}><option value="">All streams</option><option value="East">East</option><option value="West">West</option></select></div>
  <div style={{display:'grid',gridTemplateColumns:'minmax(260px,1fr) minmax(320px,1.4fr)',gap:16}}><div style={{maxHeight:360,overflowY:'auto',border:'1px solid #e2e8f0',borderRadius:10,padding:8}}>{Object.keys(grouped).length===0?<p className="muted" style={{padding:15}}>No learners match the search.</p>:Object.entries(grouped).map(([group,list])=><div key={group} style={{marginBottom:10}}><div style={{fontWeight:700,padding:'8px 10px',background:'#f3f6fa',borderRadius:7}}>{group}</div>{list.map(s=><button key={s.id} type="button" onClick={()=>choose(s)} style={{display:'block',width:'100%',textAlign:'left',padding:10,border:0,borderBottom:'1px solid #edf0f4',background:selected?.id===s.id?'#e8f1fb':'transparent',cursor:'pointer'}}><strong>{s.first_name} {s.middle_name||''} {s.last_name}</strong><br/><span style={{fontSize:12,color:'#667085'}}>{s.admission_number} · {s.class_name} · {s.stream_name}</span></button>)}</div>)}</div>
   <div style={{border:'1px solid #e2e8f0',borderRadius:10,padding:16}}>{!selected?<p className="muted">Select a learner to enter fees and payments.</p>:<><h3 style={{marginTop:0}}>{selected.first_name} {selected.middle_name||''} {selected.last_name}</h3><p className="muted" style={{marginTop:0}}><strong>{selected.admission_number}</strong> · {selected.class_name} · {selected.stream_name}</p>
    <div style={{borderTop:'1px solid #edf0f4',paddingTop:14,marginTop:12}}><h4>Termly fee account</h4><div style={{display:'flex',gap:8}}><input type="number" value={due} onChange={e=>setDue(e.target.value)} placeholder="Termly fee (auto if blank)"/><button className="btn" type="button" onClick={saveAccount} disabled={saving}>Add term fee</button></div><p className="muted" style={{fontSize:12}}>Rates: Playgroup/PP1/PP2 KES 11,000 · Grade 1–3 KES 13,500 · Grade 4–5 KES 14,000 · Grade 6–9 KES 15,000.</p></div>
    <div style={{borderTop:'1px solid #edf0f4',paddingTop:14,marginTop:16}}><h4>Record payment</h4><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><select value={paymentType} onChange={e=>setPaymentType(e.target.value)}><option value="school_fees">School fees</option><option value="other">Other payment</option></select>{paymentType==='other'?<select value={otherType} onChange={e=>setOtherType(e.target.value)}>{otherOptions.map(x=><option key={x} value={x}>{x} — KES {otherFee[x].toLocaleString()}</option>)}</select>:<div className="muted" style={{padding:10,border:'1px solid #e2e8f0',borderRadius:7}}>Termly school fees</div>}<input type="number" min="0" value={payment} onChange={e=>setPayment(e.target.value)} placeholder="Amount paid (KES)"/><select value={method} onChange={e=>setMethod(e.target.value)}><option value="mpesa">M-Pesa</option><option value="cash">Cash</option><option value="bank">Bank</option><option value="card">Card</option><option value="other">Other</option></select><input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Reference / transaction no."/><button className="btn" type="button" onClick={savePayment} disabled={saving||!payment}>{saving?'Recording…':'Record payment'}</button></div></div>
    {message&&<p style={{color:message.includes('successfully')||message.includes('generated')?'#18794e':'#b42318',fontSize:13}}>{message}</p>}{receipt&&<div className="finance-receipt" style={{marginTop:18,border:'2px solid #12385d',borderRadius:12,padding:18,background:'#fff'}}><div style={{display:'flex',alignItems:'center',gap:14,borderBottom:'1px solid #dbe3ee',paddingBottom:12}}><img src="/aic-cathedral-logo.svg" alt="AIC Cathedral Primary School" style={{width:70,height:70,objectFit:'contain'}}/><div><h3 style={{margin:0,color:'#12385d'}}>AIC CATHEDRAL PRIMARY SCHOOL</h3><div style={{fontSize:12,color:'#667085'}}>P.O. Box 37, Gilgil · Education for Excellence</div></div></div><div style={{display:'flex',justifyContent:'space-between',marginTop:14}}><strong>OFFICIAL FEE RECEIPT</strong><strong>{receipt.receipt_no}</strong></div><p><strong>Learner:</strong> {selected.first_name} {selected.middle_name||''} {selected.last_name}<br/><strong>Admission No:</strong> {selected.admission_number}</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,background:'#f5f8fc',padding:12,borderRadius:8}}><div>Amount paid<br/><strong>KES {Number(receipt.amount_paid).toLocaleString()}</strong></div><div>Balance<br/><strong>KES {Number(receipt.balance).toLocaleString()}</strong></div><div>Method<br/><strong>{receipt.payment_method.toUpperCase()}</strong></div><div>Reference<br/><strong>{receipt.reference_no||'—'}</strong></div></div><button type="button" className="btn no-print" style={{marginTop:14}} onClick={printReceipt}>Print / Save receipt</button></div>}</>}</div></div></section>}
