'use client'
import {useMemo,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'
type Student={id:string;admission_number:string;first_name:string;middle_name?:string|null;last_name:string;class_id:string|null;stream_id:string|null;class_name:string;stream_name:string}
type Receipt={receipt_no:string;amount_paid:number;balance:number;payment_method:string;reference_no:string|null;paid_at:string}
type Props={students:Student[]}
const otherOptions=['Graduation','Interview','Admission'] as const
const otherFee:Record<string,number>={Graduation:1500,Interview:500,Admission:1000}
const money=(n:number)=>Number(n||0).toLocaleString('en-KE')
const nameOf=(s:Student)=>[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(' ')
const esc=(v:any)=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c] as string))
export default function FinanceDesk({students}:Props){
 const [query,setQuery]=useState(''),[classFilter,setClassFilter]=useState(''),[streamFilter,setStreamFilter]=useState(''),[selected,setSelected]=useState<Student|null>(null)
 const [due,setDue]=useState(''),[payment,setPayment]=useState(''),[paymentType,setPaymentType]=useState('school_fees'),[otherType,setOtherType]=useState('Admission'),[method,setMethod]=useState('mpesa'),[reference,setReference]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(false),[receipt,setReceipt]=useState<Receipt|null>(null)
 const [balance,setBalance]=useState({due:0,paid:0,outstanding:0})
 const classes=useMemo(()=>Array.from(new Set(students.map(s=>s.class_name).filter(Boolean))),[students])
 const filtered=useMemo(()=>students.filter(s=>{const q=query.trim().toLowerCase();const full=`${s.first_name} ${s.middle_name||''} ${s.last_name}`.toLowerCase();return(!q||s.admission_number.toLowerCase().includes(q)||full.includes(q))&&(!classFilter||s.class_name===classFilter)&&(!streamFilter||s.stream_name===streamFilter)}),[students,query,classFilter,streamFilter])
 const grouped=useMemo(()=>filtered.reduce<Record<string,Student[]>>((a,s)=>{const key=`${s.class_name} — ${s.stream_name}`;(a[key]??=[]).push(s);return a},{}),[filtered])
 const refreshBalance=async(s:Student)=>{const db=createClient();const{data}=await db.from('fee_accounts').select('amount_due,amount_paid').eq('student_id',s.id);const rows=data||[];const d=rows.reduce((n,x)=>n+Number(x.amount_due||0),0);const p=rows.reduce((n,x)=>n+Number(x.amount_paid||0),0);setBalance({due:d,paid:p,outstanding:Math.max(d-p,0)})}
 const choose=(s:Student)=>{setSelected(s);setMessage('');setDue('');setPayment('');setReference('');setReceipt(null);setPaymentType('school_fees');setOtherType('Admission');setBalance({due:0,paid:0,outstanding:0});refreshBalance(s)}
 const saveAccount=async()=>{if(!selected)return;setSaving(true);setMessage('');const db=createClient();const{data:term}=await db.from('terms').select('id,name').eq('is_current',true).eq('status','active').order('start_date',{ascending:false}).limit(1).maybeSingle();const{data:year}=await db.from('academic_years').select('id').eq('is_current',true).eq('status','active').order('year',{ascending:false}).limit(1).maybeSingle();const termFee=Number(due);if(!termFee){setMessage('Enter the termly fee amount.');setSaving(false);return}const{error}=await db.from('fee_accounts').insert({student_id:selected.id,academic_year_id:year?.id||null,term_id:term?.id||null,amount_due:termFee,amount_paid:0,status:'unpaid',charge_type:'term_fee',charge_label:'Termly school fees'});setMessage(error?error.message:'Termly fee account saved successfully.');if(!error)await refreshBalance(selected);setSaving(false)}
 const savePayment=async()=>{if(!selected||!payment)return;setSaving(true);setMessage('');setReceipt(null);const db=createClient();let accountId:string|null=null;let category='school_fees';let amountDue=0;
 if(paymentType==='school_fees'){const{data:term}=await db.from('terms').select('id,name').eq('is_current',true).eq('status','active').order('start_date',{ascending:false}).limit(1).maybeSingle();const{data:year}=await db.from('academic_years').select('id').eq('is_current',true).eq('status','active').order('year',{ascending:false}).limit(1).maybeSingle();const{data:existing}=await db.from('fee_accounts').select('id,amount_due,amount_paid').eq('student_id',selected.id).eq('charge_type','term_fee').eq('term_id',term?.id||'').order('created_at',{ascending:false}).limit(1).maybeSingle();if(existing?.id)accountId=existing.id;else{amountDue=Number(due)||0;if(!amountDue){const{data:fee}=await db.rpc('school_term_fee',{p_class_name:selected.class_name});amountDue=Number(fee||0)}if(!amountDue){setMessage('No fee structure was found for this class.');setSaving(false);return}const created=await db.from('fee_accounts').insert({student_id:selected.id,academic_year_id:year?.id||null,term_id:term?.id||null,amount_due:amountDue,amount_paid:0,status:'unpaid',charge_type:'term_fee',charge_label:'Termly school fees'}).select('id').single();if(created.error||!created.data?.id){setMessage(created.error?.message||'Fee account could not be created.');setSaving(false);return}accountId=created.data.id}}
 else{category=otherType.toLowerCase();amountDue=otherFee[otherType];const{data:term}=await db.from('terms').select('id,name').eq('is_current',true).eq('status','active').order('start_date',{ascending:false}).limit(1).maybeSingle();const{data:year}=await db.from('academic_years').select('id').eq('is_current',true).eq('status','active').order('year',{ascending:false}).limit(1).maybeSingle();const termNumber=Number(String(term?.name||'').match(/\d+/)?.[0]||0);if(otherType==='Graduation'&&selected.class_name!=='PP2'){setMessage('Graduation Fee is only for PP2.');setSaving(false);return}if(otherType==='Interview'&&!/^Grade [1-9]$/.test(selected.class_name)){setMessage('Interview Fee is for Grades 1–9 new learners.');setSaving(false);return}if(otherType==='Graduation'&&termNumber!==3){setMessage('Graduation Fee is payable in 3rd Term.');setSaving(false);return}const created=await db.from('fee_accounts').insert({student_id:selected.id,academic_year_id:year?.id||null,term_id:term?.id||null,amount_due:amountDue,amount_paid:0,status:'unpaid',charge_type:category,charge_label:`${otherType} Fee`}).select('id').single();if(created.error||!created.data?.id){setMessage(created.error?.message||'Other fee account could not be created.');setSaving(false);return}accountId=created.data.id}
 const{data:paymentRow,error}=await db.from('fee_payments').insert({student_id:selected.id,fee_account_id:accountId,amount:Number(payment),payment_method:method,reference_no:reference||null,payment_category:category}).select('id').single();if(error||!paymentRow){setMessage(error?.message||'Payment could not be recorded.');setSaving(false);return}
 const{data:r}=await db.from('fee_receipts').select('receipt_no,amount_paid,balance,payment_method,reference_no,paid_at').eq('payment_id',paymentRow.id).single();await refreshBalance(selected);setReceipt(r as Receipt|null);setMessage(r?'Payment recorded and receipt generated automatically.':'Payment recorded successfully.');setPayment('');setReference('');setSaving(false)}
 const printReceipt=()=>{if(typeof window!=='undefined')window.print()}
 const printBalanceInvoice=()=>{if(!selected||balance.outstanding<=0)return;const w=window.open('','_blank','width=900,height=800');if(!w)return;w.document.write(`<!doctype html><html><head><title>Balance Invoice - ${esc(nameOf(selected))}</title><style>@page{margin:14mm}body{font-family:Arial,sans-serif;padding:34px;color:#172033}header{display:flex;align-items:center;gap:16px;border-bottom:5px solid #b8860b;padding-bottom:15px}header img{width:72px;height:72px;object-fit:contain}h1{margin:0;color:#12385d;font-size:25px}.meta{color:#667085;font-size:12px}.learner{margin-top:28px;padding:18px;border:1px solid #d8dee8;border-radius:12px}.balance{margin-top:28px;padding:28px;border:2px solid #b8860b;border-radius:14px;text-align:center;background:#fffaf0}.label{font-size:13px;color:#667085}.amount{font-size:38px;font-weight:900;color:#12385d;margin-top:8px}.notice{margin-top:22px;padding:15px;background:#f7f9fc;border-radius:10px;font-size:13px}footer{margin-top:50px;padding-top:14px;border-top:1px solid #d8dee8;font-size:11px;color:#667085}@media print{body{padding:0}}</style></head><body><header><img src="${location.origin}/aic-cathedral-logo.svg"><div><h1>AIC CATHEDRAL PRIMARY SCHOOL</h1><div class="meta">P.O. Box 37, Gilgil · Education for Excellence</div></div></header><div class="learner"><strong>LEARNER</strong><br>${esc(nameOf(selected))}<br><span class="meta">Admission No.: ${esc(selected.admission_number)} · ${esc(selected.class_name)} · ${esc(selected.stream_name)}</span></div><div class="balance"><div class="label">OUTSTANDING SCHOOL FEES BALANCE</div><div class="amount">KES ${money(balance.outstanding)}</div></div><div class="notice">This invoice shows <strong>only the unpaid balance</strong> currently outstanding on the learner's fee account. It does not include amounts already paid.</div><footer>Please quote the learner admission number when making payment. Generated ${esc(new Date().toLocaleString())}.</footer><script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body></html>`);w.document.close()}
 return <section className="card" style={{marginBottom:16}}><div style={{marginBottom:16}}><h2 style={{marginBottom:4}}>Fee collection desk</h2><p className="muted">The school fee structure is applied automatically by class. Record the amount paid and the system calculates the outstanding balance.</p></div>
  <div style={{display:'grid',gridTemplateColumns:'minmax(220px,2fr) repeat(2,minmax(150px,1fr))',gap:10,marginBottom:18}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search admission number or student name"/><select value={classFilter} onChange={e=>setClassFilter(e.target.value)}><option value="">All grades/classes</option>{classes.map(c=><option key={c}>{c}</option>)}</select><select value={streamFilter} onChange={e=>setStreamFilter(e.target.value)}><option value="">All streams</option><option value="East">East</option><option value="West">West</option></select></div>
  <div style={{display:'grid',gridTemplateColumns:'minmax(260px,1fr) minmax(320px,1.4fr)',gap:16}}><div style={{maxHeight:360,overflowY:'auto',border:'1px solid #e2e8f0',borderRadius:10,padding:8}}>{Object.keys(grouped).length===0?<p className="muted" style={{padding:15}}>No learners match the search.</p>:Object.entries(grouped).map(([group,list])=><div key={group} style={{marginBottom:10}}><div style={{fontWeight:700,padding:'8px 10px',background:'#f3f6fa',borderRadius:7}}>{group}</div>{list.map(s=><button key={s.id} type="button" onClick={()=>choose(s)} style={{display:'block',width:'100%',textAlign:'left',padding:10,border:0,borderBottom:'1px solid #edf0f4',background:selected?.id===s.id?'#e8f1fb':'transparent',cursor:'pointer'}}><strong>{nameOf(s)}</strong><br/><span style={{fontSize:12,color:'#667085'}}>{s.admission_number} · {s.class_name} · {s.stream_name}</span></button>)}</div>)}</div>
   <div style={{border:'1px solid #e2e8f0',borderRadius:10,padding:16}}>{!selected?<p className="muted">Select a learner to enter fees and payments.</p>:<><h3 style={{marginTop:0}}>{nameOf(selected)}</h3><p className="muted" style={{marginTop:0}}><strong>{selected.admission_number}</strong> · {selected.class_name} · {selected.stream_name}</p>
    <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8,margin:'14px 0'}}><div style={{padding:12,background:'#f5f8fc',borderRadius:9}}><small>Fees Due</small><strong style={{display:'block'}}>KES {money(balance.due)}</strong></div><div style={{padding:12,background:'#f5f8fc',borderRadius:9}}><small>Total Paid</small><strong style={{display:'block'}}>KES {money(balance.paid)}</strong></div><div style={{padding:12,background:balance.outstanding?'#fff5f5':'#effaf3',borderRadius:9}}><small>Balance</small><strong style={{display:'block'}}>KES {money(balance.outstanding)}</strong></div></div>
    <div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:16}}>{balance.outstanding>0?<button className="btn" type="button" onClick={printBalanceInvoice}>🧾 Print / Download Balance Invoice</button>:<span style={{fontWeight:700,color:'#18794e',padding:'9px 0'}}>✓ No outstanding balance</span>}</div>
    <div style={{borderTop:'1px solid #edf0f4',paddingTop:14,marginTop:12}}><h4>Termly fee account</h4><div style={{display:'flex',gap:8}}><input type="number" value={due} onChange={e=>setDue(e.target.value)} placeholder="Termly fee (auto if blank)"/><button className="btn" type="button" onClick={saveAccount} disabled={saving}>Add term fee</button></div><p className="muted" style={{fontSize:12}}>Rates: Playgroup/PP1/PP2 KES 11,000 · Grade 1–3 KES 13,500 · Grade 4–5 KES 14,000 · Grade 6–9 KES 15,000.</p></div>
    <div style={{borderTop:'1px solid #edf0f4',paddingTop:14,marginTop:16}}><h4>Record payment</h4><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><select value={paymentType} onChange={e=>setPaymentType(e.target.value)}><option value="school_fees">School fees</option><option value="other">Other payment</option></select>{paymentType==='other'?<select value={otherType} onChange={e=>setOtherType(e.target.value)}>{otherOptions.map(x=><option key={x} value={x}>{x} — KES {otherFee[x].toLocaleString()}</option>)}</select>:<div className="muted" style={{padding:10,border:'1px solid #e2e8f0',borderRadius:7}}>Termly school fees</div>}<input type="number" min="0" value={payment} onChange={e=>setPayment(e.target.value)} placeholder="Amount paid (KES)"/><select value={method} onChange={e=>setMethod(e.target.value)}><option value="mpesa">M-Pesa</option><option value="cash">Cash</option><option value="bank">Bank</option><option value="card">Card</option><option value="other">Other</option></select><input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Reference / transaction no."/><button className="btn" type="button" onClick={savePayment} disabled={saving||!payment}>{saving?'Recording…':'Record payment'}</button></div></div>
    {message&&<p style={{color:message.includes('successfully')||message.includes('generated')?'#18794e':'#b42318',fontSize:13}}>{message}</p>}{receipt&&<div className="finance-receipt" style={{marginTop:18,border:'2px solid #12385d',borderRadius:12,padding:18,background:'#fff'}}><div style={{display:'flex',alignItems:'center',gap:14,borderBottom:'1px solid #dbe3ee',paddingBottom:12}}><img src="/aic-cathedral-logo.svg" alt="AIC Cathedral Primary School" style={{width:70,height:70,objectFit:'contain'}}/><div><h3 style={{margin:0,color:'#12385d'}}>AIC CATHEDRAL PRIMARY SCHOOL</h3><div style={{fontSize:12,color:'#667085'}}>P.O. Box 37, Gilgil · Education for Excellence</div></div></div><div style={{display:'flex',justifyContent:'space-between',marginTop:14}}><strong>OFFICIAL FEE RECEIPT</strong><strong>{receipt.receipt_no}</strong></div><p><strong>Learner:</strong> {nameOf(selected)}<br/><strong>Admission No:</strong> {selected.admission_number}</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8,background:'#f5f8fc',padding:12,borderRadius:8}}><div>Amount paid<br/><strong>KES {money(receipt.amount_paid)}</strong></div><div>Balance<br/><strong>KES {money(receipt.balance)}</strong></div><div>Method<br/><strong>{receipt.payment_method.toUpperCase()}</strong></div><div>Reference<br/><strong>{receipt.reference_no||'—'}</strong></div></div><button type="button" className="btn no-print" style={{marginTop:14}} onClick={printReceipt}>Print / Save receipt</button></div>}</>}</div></div></section>}
