'use client'
import {useEffect,useMemo,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'
type Student={id:string;first_name:string;middle_name?:string|null;last_name:string;admission_number:string}
type Account={student_id:string;amount_due:number;amount_paid:number;status:string;charge_label?:string|null}
const nameOf=(s?:Student)=>s?[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(' '):'Unknown learner'
const esc=(v:any)=>String(v??'—').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c] as string))
export default function Invoices(){const[students,setStudents]=useState<Student[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true)
 const load=async()=>{const db=createClient();const[{data:s},{data:a}]=await Promise.all([db.from('students').select('id,first_name,middle_name,last_name,admission_number').eq('status','active').order('last_name'),db.from('fee_accounts').select('student_id,amount_due,amount_paid,status,charge_label').order('created_at',{ascending:false})]);setStudents((s||[]) as Student[]);setAccounts((a||[]) as Account[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const rows=useMemo(()=>{const q=query.trim().toLowerCase();return students.filter(s=>!q||nameOf(s).toLowerCase().includes(q)||s.admission_number.toLowerCase().includes(q)).map(s=>{const a=accounts.filter(x=>x.student_id===s.id);const due=a.reduce((n,x)=>n+Number(x.amount_due||0),0);const paid=a.reduce((n,x)=>n+Number(x.amount_paid||0),0);return{s,due,paid,balance:Math.max(due-paid,0)}})},[students,accounts,query])
 const pdf=(s:Student,due:number,paid:number,balance:number)=>{const w=window.open('','_blank','width=1000,height=900');if(!w)return;w.document.write(`<!doctype html><html><head><title>Fee Balance Invoice - ${esc(nameOf(s))}</title><style>@page{margin:12mm}body{font-family:Arial,sans-serif;padding:32px;color:#172033}header{display:flex;align-items:center;gap:16px;border-bottom:5px solid #b8860b;padding-bottom:15px}header img{width:72px;height:72px;object-fit:contain}h1{margin:0;color:#12385d;font-size:25px}h2{color:#b8860b}.meta{color:#667085;font-size:12px}.box{padding:18px;background:#f5f8fc;border-radius:12px;margin-top:20px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:20px}.amount{font-size:22px;font-weight:800;color:#12385d;margin-top:5px}.balance{margin-top:25px;padding:20px;border-left:6px solid #b8860b;background:#fff8e7;font-size:24px;font-weight:800;color:#12385d}.tag{display:inline-block;padding:7px 12px;border-radius:999px;background:#e8f2fb;color:#0757a6;font-weight:700}footer{margin-top:45px;color:#667085;font-size:12px;border-top:1px solid #d8dee8;padding-top:12px}@media print{body{padding:0}}</style></head><body><header><img src="${location.origin}/aic-cathedral-logo.svg"><div><h1>AIC CATHEDRAL PRIMARY SCHOOL</h1><div class="meta">P.O. Box 37, Gilgil · Education for Excellence</div></div></header><div style="display:flex;justify-content:space-between;align-items:center;margin-top:25px"><div><h2 style="margin:0">FEE BALANCE INVOICE</h2><div class="tag">${esc(`INV-${s.admission_number}-${new Date().getFullYear()}`)}</div></div><div class="meta">Date: ${esc(new Date().toLocaleDateString())}</div></div><div class="box"><b>Billed to</b><br>${esc(nameOf(s))}<br>Admission No.: ${esc(s.admission_number)}</div><div class="grid"><div class="box"><div class="meta">TOTAL FEES DUE</div><div class="amount">KES ${due.toLocaleString('en-KE')}</div></div><div class="box"><div class="meta">TOTAL PAID</div><div class="amount">KES ${paid.toLocaleString('en-KE')}</div></div><div class="box"><div class="meta">OUTSTANDING</div><div class="amount">KES ${balance.toLocaleString('en-KE')}</div></div></div><div class="balance">OUTSTANDING BALANCE: KES ${balance.toLocaleString('en-KE')}</div><footer>This balance invoice reflects the learner's current fee accounts. Please use the learner's name and class on payment slips.</footer><script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body></html>`);w.document.close()}
 return <section className="card"><div><h2 style={{margin:0}}>Learner balance invoices</h2><p className="muted" style={{margin:'5px 0'}}>Print or save a professional invoice showing each child's total fees, payments and current outstanding balance.</p></div><input style={{margin:'14px 0',maxWidth:420}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search learner name or admission number"/><div style={{overflowX:'auto'}}><table className="prototype-table"><thead><tr><th>Learner</th><th>Admission No.</th><th>Total Due</th><th>Paid</th><th>Balance</th><th>Status</th><th>Invoice</th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="prototype-empty">Loading…</td></tr>:rows.length?rows.map(r=><tr key={r.s.id}><td><strong>{nameOf(r.s)}</strong></td><td>{r.s.admission_number}</td><td>KES {r.due.toLocaleString('en-KE')}</td><td>KES {r.paid.toLocaleString('en-KE')}</td><td><strong>KES {r.balance.toLocaleString('en-KE')}</strong></td><td>{r.balance===0?'PAID':r.paid>0?'PARTIAL':'UNPAID'}</td><td><button className="btn secondary" type="button" onClick={()=>pdf(r.s,r.due,r.paid,r.balance)}>Print / Save Invoice</button></td></tr>):<tr><td colSpan={7} className="prototype-empty">No learners found.</td></tr>}</tbody></table></div></section>}
