'use client'

import {useEffect,useMemo,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'

type Receipt={id:string;receipt_no:string;student_id:string;amount_paid:number;balance:number;payment_method:string;reference_no:string|null;paid_at:string}
type Student={id:string;first_name:string;middle_name?:string|null;last_name:string;admission_number:string;class_id:string|null;stream_id:string|null}
const LOGO='https://res.cloudinary.com/c4bk5bio/image/upload/v1789683108/aic-cathedral/branding/aic-cathedral-official-logo.png'
const nameOf=(s?:Student)=>s?[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(' '):'Unknown learner'
const money=(n:number)=>Number(n||0).toLocaleString('en-KE')
const esc=(v:any)=>String(v??'—').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c] as string))

export default function OfficialThermalFeeReceipts(){
 const[rows,setRows]=useState<Receipt[]>([]),[students,setStudents]=useState<Student[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('')
 const[classes,setClasses]=useState<Record<string,string>>({}),[streams,setStreams]=useState<Record<string,string>>({})
 const map=useMemo(()=>new Map(students.map(s=>[s.id,s])),[students])
 const load=async()=>{setLoading(true);const db=createClient();const[{data:r,error:re},{data:s,error:se},{data:c},{data:st}]=await Promise.all([db.from('fee_receipts').select('id,receipt_no,student_id,amount_paid,balance,payment_method,reference_no,paid_at').order('created_at',{ascending:false}),db.from('students').select('id,first_name,middle_name,last_name,admission_number,class_id,stream_id').eq('status','active').order('last_name'),db.from('classes').select('id,name').eq('status','active'),db.from('streams').select('id,name').eq('status','active')]);if(re||se)setMessage(re?.message||se?.message||'Could not load receipts.');else{setRows((r||[]) as Receipt[]);setStudents((s||[]) as Student[]);setClasses(Object.fromEntries((c||[]).map(x=>[x.id,x.name])));setStreams(Object.fromEntries((st||[]).map(x=>[x.id,x.name])))}setLoading(false)}
 useEffect(()=>{load()},[])
 const print=(r:Receipt)=>{const s=map.get(r.student_id);const w=window.open('','_blank','width=420,height=800');if(!w)return;const grade=s?.class_id?classes[s.class_id]||'':'',stream=s?.stream_id?streams[s.stream_id]||'':'';const logo=LOGO;w.document.write(`<!doctype html><html><head><title>School Fees Receipt ${esc(r.receipt_no)}</title><style>@page{size:80mm auto;margin:0}body{width:80mm;margin:0 auto;padding:5mm 4mm;font-family:Arial,sans-serif;font-size:11px;color:#111}.center{text-align:center}.logo{width:28mm;height:28mm;object-fit:contain;display:block;margin:0 auto 2mm}.school{font-weight:900;font-size:14px;line-height:1.1;text-transform:uppercase}.title{font-weight:900;font-size:13px;margin:2mm 0;text-align:center}.rule{border-top:1px dashed #111;margin:3mm 0}.row{display:flex;justify-content:space-between;gap:4mm;margin:1.4mm 0}.label{font-weight:700}.amount{font-size:18px;font-weight:900}.balance{font-size:14px;font-weight:900}.small{font-size:9px}.thanks{text-align:center;font-weight:700;margin-top:3mm}</style></head><body><div class="center"><img class="logo" src="${logo}" alt="AIC Cathedral School logo"><div class="school">${esc('AIC Cathedral Comprehensive School')}</div><div>${esc('Gilgil, Nakuru County, Kenya')}</div></div><div class="rule"></div><div class="title">School Fees Payment Receipt</div><div class="rule"></div><div class="row"><span class="label">Receipt No.</span><span>${esc(r.receipt_no)}</span></div><div class="row"><span class="label">Date</span><span>${esc(new Date(r.paid_at).toLocaleDateString('en-KE'))}</span></div><div class="row"><span class="label">Time</span><span>${esc(new Date(r.paid_at).toLocaleTimeString('en-KE'))}</span></div><div class="rule"></div><div class="row"><span class="label">Student</span><span>${esc(nameOf(s))}</span></div><div class="row"><span class="label">Admission</span><span>${esc(s?.admission_number)}</span></div>${grade?`<div class="row"><span class="label">Grade</span><span>${esc(grade)}</span></div>`:''}${stream?`<div class="row"><span class="label">Stream</span><span>${esc(stream)}</span></div>`:''}<div class="rule"></div><div class="row"><span class="label">Payment</span><span>${esc(r.payment_method.replace(/^bank_/,'Bank — ').toUpperCase())}</span></div><div class="row"><span class="label">Reference</span><span>${esc(r.reference_no||'—')}</span></div><div class="rule"></div><div class="row"><span>Amount Paid</span><span class="amount">KES ${money(r.amount_paid)}</span></div><div class="row"><span>Balance Due</span><span class="balance">KES ${money(r.balance)}</span></div><div class="rule"></div><div class="thanks">Payment received successfully.</div><div class="thanks">Thank you for your payment.</div><div class="small center">Keep this receipt for your records.</div><script>const i=document.querySelector('.logo');const go=()=>setTimeout(()=>window.print(),200);if(i.complete)go();else{i.onload=go;i.onerror=go;setTimeout(go,1800)}</script></body></html>`);w.document.close()}
 return <section className="card"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',marginBottom:16}}><div><h2 style={{margin:0}}>School Fees Receipts</h2><p className="muted" style={{margin:'5px 0 0'}}>Automatic compact receipts for 58mm/80mm thermal printers. Every recorded fee payment receives an automatic receipt number.</p></div>{rows[0]&&<button type="button" className="btn" onClick={()=>print(rows[0])}>Print latest receipt</button>}</div>{message&&<p style={{color:'#b42318'}}>{message}</p>}<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Receipt No.','Student','Admission No.','Amount Paid','Balance Due','Method','Date','Action'].map(h=><th key={h} style={{textAlign:'left',padding:10}}>{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={8} style={{padding:25}}>Loading receipts…</td></tr>:rows.length?rows.map(r=>{const s=map.get(r.student_id);return <tr key={r.id}><td style={{padding:10,fontWeight:700}}>{r.receipt_no}</td><td style={{padding:10}}>{nameOf(s)}</td><td style={{padding:10}}>{s?.admission_number||'—'}</td><td style={{padding:10}}>KES {money(r.amount_paid)}</td><td style={{padding:10}}>KES {money(r.balance)}</td><td style={{padding:10}}>{r.payment_method.replace(/^bank_/,'Bank — ').toUpperCase()}</td><td style={{padding:10}}>{new Date(r.paid_at).toLocaleString('en-KE')}</td><td style={{padding:10}}><button type="button" className="btn secondary" onClick={()=>print(r)}>Print Receipt</button></td></tr>}) : <tr><td colSpan={8} className="muted" style={{padding:30,textAlign:'center'}}>No fee receipts have been generated yet.</td></tr>}</tbody></table></div></section>
}
