import {createClient} from '../../../lib/supabase/server'
import FinanceDesk from './finance-desk'
import SimpleCrud from '../_components/simple-crud'
import { PrototypePage, PrototypePanel, PrototypeBadge } from '../_components/prototype-workspace'
export default async function Page(){
 const s=await createClient();const [{data:students},{data:academicYear},{data:accounts},{data:payments}]=await Promise.all([s.from('students').select('id,admission_number,first_name,middle_name,last_name,class_id,stream_id').eq('status','active').order('last_name'),s.from('academic_years').select('id').eq('status','active').order('year',{ascending:false}).limit(1).maybeSingle(),s.from('fee_accounts').select('amount_due,amount_paid,status,student_id'),s.from('fee_payments').select('amount')]);const [{data:classes},{data:streams}]=await Promise.all([s.from('classes').select('id,name').eq('status','active'),s.from('streams').select('id,class_id,name').eq('status','active')]);const cm=new Map((classes||[]).map(c=>[c.id,c.name])),sm=new Map((streams||[]).map(x=>[x.id,x.name]));const fs=(students||[]).map(x=>({...x,class_name:cm.get(x.class_id||'')||'Unassigned',stream_name:sm.get(x.stream_id||'')||'Unassigned'}));const opts=fs.map(x=>({value:x.id,label:`${x.admission_number} — ${x.first_name} ${x.middle_name?`${x.middle_name} `:''}${x.last_name}`}));const learnerLabels=Object.fromEntries(fs.map(x=>[x.id,`${x.first_name} ${x.middle_name?`${x.middle_name} `:''}${x.last_name} (${x.admission_number})`]));const due=(accounts||[]).reduce((a,x)=>a+Number(x.amount_due||0),0),paid=(accounts||[]).reduce((a,x)=>a+Number(x.amount_paid||0),0)||(payments||[]).reduce((a,x)=>a+Number(x.amount||0),0),holds=(accounts||[]).filter(x=>['unpaid','partial'].includes(String(x.status))).length;return <PrototypePage title="Finance & Fees" subtitle="Fees, payments, arrears, invoices and fee-hold management" action={<a href="#payment" className="prototype-primary-button">+ Record Payment</a>} kpis={[{label:'Total Collected',value:`KES ${paid.toLocaleString('en-KE')}`,note:'Live recorded payments',tone:'navy'},{label:'Total Arrears',value:`KES ${Math.max(due-paid,0).toLocaleString('en-KE')}`,note:'Outstanding balances',tone:'green'},{label:'Fee-Hold Students',value:holds,note:'Linked to transport/teachers',tone:'red'},{label:'Payments Recorded',value:(payments||[]).length,note:'Payment entries',tone:'yellow'}]} tabs={[["#overview","Overview & Fee Structure"],["#payment","Payments & Receipts"],["#balances","Balances & Fee Hold"],["#discounts","Discounts & Invoices"]]}>
 <section id="overview"><FinanceDesk students={fs} academicYearId={academicYear?.id}/></section>
 <section id="payment"><SimpleCrud table="finance_banks" title="Banks used by the school" fields={[{name:'bank_name',label:'Bank',options:['Equity Bank','Co-operative Bank','KCB'],required:true},{name:'account_name',label:'Account name'},{name:'account_number',label:'Account number'},{name:'branch',label:'Branch'},{name:'active',label:'Active',type:'boolean',options:['true','false']}]} /></section>
 <section id="balances"><SimpleCrud table="fee_accounts" title="Learner fee accounts" roleHint="Fee-hold records should be visible to teaching and transport workflows." valueLabels={{student_id:learnerLabels}} fields={[{name:'student_id',label:'Learner',required:true,options:opts},{name:'amount_due',label:'Amount due (KES)',type:'number',required:true},{name:'amount_paid',label:'Amount paid (KES)',type:'number'},{name:'status',label:'Status',options:['unpaid','partial','paid','waived']}]} /></section>
 <section id="payment-history"><SimpleCrud table="fee_payments" title="Fees collected & receipts" valueLabels={{student_id:learnerLabels}} fields={[{name:'student_id',label:'Learner',required:true,options:opts},{name:'amount',label:'Amount (KES)',type:'number',required:true},{name:'payment_method',label:'Method',options:['cash','mpesa','bank','card','other']},{name:'reference_no',label:'Reference / receipt no.'}]} /></section>
 <section id="discounts"><SimpleCrud table="other_income" title="Other income / invoices" fields={[{name:'income_date',label:'Date',type:'date'},{name:'source',label:'Source',required:true},{name:'description',label:'Description'},{name:'amount',label:'Amount (KES)',type:'number',required:true},{name:'reference_no',label:'Reference'}]} /></section>
 </PrototypePage>}
