'use client'

import {useEffect,useMemo,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'

type Student={id:string;first_name:string;middle_name?:string|null;last_name:string;admission_number:string}
type Account={student_id:string;amount_due:number;amount_paid:number;status:string;created_at:string}
type Payment={student_id:string;amount:number;payment_method:string;reference_no:string|null;paid_at:string|null}

const nameOf=(s?:Student)=>s?[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(' '):'Unknown learner'
const esc=(v:any)=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c] as string))

function printStatement(student:Student,accounts:Account[],payments:Payment[]){
 const mine=accounts.filter(a=>a.student_id===student.id)
 const paid=mine.reduce((n,a)=>n+Number(a.amount_paid||0),0)
 const due=mine.reduce((n,a)=>n+Number(a.amount_due||0),0)
 const balance=Math.max(due-paid,0)
 const pays=payments.filter(p=>p.student_id===student.id)
 const rows=pays.map(p=>`<tr><td>${esc(p.paid_at?new Date(p.paid_at).toLocaleDateString():'—')}</td><td>${esc(p.payment_method.toUpperCase())}</td><td>${esc(p.reference_no||'—')}</td><td>KES ${Number(p.amount||0).toLocaleString('en-KE')}</td></tr>`).join('')
 const w=window.open('','_blank','width=1000,height=900');if(!w)return
 w.document.write(`<!doctype html><html><head><title>Fee Statement - ${esc(nameOf(student))}</title><style>@page{margin:14mm}body{font-family:Arial,sans-serif;padding:30px;color:#172033}header{display:flex;align-items:center;gap:16px;border-bottom:5px solid #b8860b;padding-bottom:14px}header img{width:72px;height:72px;object-fit:contain}h1{margin:0;color:#12385d;font-size:24px}h2{color:#b8860b;margin:24px 0 5px}.muted{color:#667085;font-size:12px}.hero{margin-top:20px;display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.box{padding:16px;border:1px solid #d8dee8;border-radius:10px;background:#f7f9fc}.label{font-size:11px;color:#667085}.amount{font-size:22px;font-weight:800;color:#12385d;margin-top:4px}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{padding:10px;border:1px solid #d0d7e2;text-align:left}th{background:#12385d;color:white}.balance{margin-top:18px;padding:14px 18px;border-left:5px solid #b8860b;background:#fff8e7;font-weight:700}.footer{margin-top:35px;border-top:1px solid #d0d7e2;padding-top:12px;font-size:11px;color:#667085}@media print{body{padding:0}}</style></head><body><header><img src="${location.origin}/aic-cathedral-logo.svg"><div><h1>AIC CATHEDRAL PRIMARY SCHOOL</h1><div class="muted">Official Learner Fee Statement</div></div></header><h2>${esc(nameOf(student))}</h2><div class="muted">Admission No.: ${esc(student.admission_number)} · Generated ${esc(new Date().toLocaleString())}</div><div class="hero"><div class="box"><div class="label">TOTAL FEES DUE</div><div class="amount">KES ${due.toLocaleString('en-KE')}</div></div><div class="box"><div class="label">TOTAL PAID</div><div class="amount">KES ${paid.toLocaleString('en-KE')}</div></div><div class="box"><div class="label">BALANCE</div><div class="amount">KES ${balance.toLocaleString('en-KE')}</div></div></div><div class="balance">${balance>0?`Pending school fees: KES ${balance.toLocaleString('en-KE')}`:'Fee account is fully paid based on the current account records.'}</div><h2>Payment History</h2><table><thead><tr><th>Date</th><th>Method</th><th>Reference / Receipt</th><th>Amount</th></tr></thead><tbody>${rows||'<tr><td colspan="4">No payments recorded.</td></tr>'}</tbody></table><h2>Fee Accounts</h2><table><thead><tr><th>Account Date</th><th>Amount Due</th><th>Amount Paid</th><th>Status</th></tr></thead><tbody>${mine.map(a=>`<tr><td>${esc(new Date(a.created_at).toLocaleDateString())}</td><td>KES ${Number(a.amount_due||0).toLocaleString('en-KE')}</td><td>KES ${Number(a.amount_paid||0).toLocaleString('en-KE')}</td><td>${esc(String(a.status).toUpperCase())}</td></tr>`).join('')||'<tr><td colspan="4">No fee account recorded.</td></tr>'}</tbody></table><div class="footer">This is an official AIC Cathedral fee statement. Please retain this statement and quote the learner admission number on fee enquiries.</div><script>window.onload=()=>setTimeout(()=>window.print(),250)</script></body></html>`)
 w.document.close()
}

export default function StudentFeeStatements(){
 const [students,setStudents]=useState<Student[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[payments,setPayments]=useState<Payment[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true)
 useEffect(()=>{(async()=>{const db=createClient();const [{data:s},{data:a},{data:p}]=await Promise.all([db.from('students').select('id,first_name,middle_name,last_name,admission_number').eq('status','active').order('last_name'),db.from('fee_accounts').select('student_id,amount_due,amount_paid,status,created_at').order('created_at',{ascending:false}),db.from('fee_payments').select('student_id,amount,payment_method,reference_no,paid_at').order('paid_at',{ascending:false})]);setStudents((s||[]) as Student[]);setAccounts((a||[]) as Account[]);setPayments((p||[]) as Payment[]);setLoading(false)})()},[])
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return students.filter(s=>!q||nameOf(s).toLowerCase().includes(q)||s.admission_number.toLowerCase().includes(q))},[students,query])
 const printAll=()=>filtered.forEach((s,i)=>setTimeout(()=>printStatement(s,accounts,payments),i*400))
 return <section className="card" style={{marginTop:16}}><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><h2 style={{margin:0}}>Student fee statements</h2><p className="muted" style={{margin:'5px 0 0'}}>Bursar can print a complete fee statement for any learner, including payments, receipts, fees due and balance.</p></div><button type="button" className="btn secondary" onClick={printAll} disabled={!filtered.length}>Print all statements</button></div><input style={{margin:'14px 0',maxWidth:420}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search learner name or admission number"/><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th style={{textAlign:'left',padding:10}}>Learner</th><th style={{textAlign:'left',padding:10}}>Admission No.</th><th style={{textAlign:'left',padding:10}}>Fees Due</th><th style={{textAlign:'left',padding:10}}>Paid</th><th style={{textAlign:'left',padding:10}}>Balance</th><th style={{textAlign:'left',padding:10}}>Action</th></tr></thead><tbody>{loading?<tr><td colSpan={6} style={{padding:25}}>Loading…</td></tr>:filtered.length?filtered.map(s=>{const a=accounts.filter(x=>x.student_id===s.id);const due=a.reduce((n,x)=>n+Number(x.amount_due||0),0);const paid=a.reduce((n,x)=>n+Number(x.amount_paid||0),0);return <tr key={s.id}><td style={{padding:10}}><strong>{nameOf(s)}</strong></td><td style={{padding:10}}>{s.admission_number}</td><td style={{padding:10}}>KES {due.toLocaleString('en-KE')}</td><td style={{padding:10}}>KES {paid.toLocaleString('en-KE')}</td><td style={{padding:10}}>KES {Math.max(due-paid,0).toLocaleString('en-KE')}</td><td style={{padding:10}}><button type="button" className="btn secondary" onClick={()=>printStatement(s,accounts,payments)}>Print / PDF</button></td></tr>}) : <tr><td colSpan={6} className="muted" style={{padding:30,textAlign:'center'}}>No learners found.</td></tr>}</tbody></table></div></section>
}
