'use client'

import {useEffect,useMemo,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'

type Receipt={id:string;receipt_no:string;payment_id:string;student_id:string;amount_paid:number;balance:number;payment_method:string;reference_no:string|null;paid_at:string}
type Student={id:string;first_name:string;middle_name?:string|null;last_name:string;admission_number:string;class_id:string|null;stream_id:string|null}
type School={school_name:string;address:string|null;logo_url:string|null;currency:string}

const OFFICIAL_LOGO='https://res.cloudinary.com/c4bk5bio/image/upload/v1789683108/aic-cathedral/branding/aic-cathedral-official-logo.png'
const nameOf=(s?:Student)=>s?[s.first_name,s.middle_name,s.last_name].filter(Boolean).join(' '):'Unknown learner'
const money=(n:number)=>Number(n||0).toLocaleString('en-KE')
const esc=(v:any)=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c] as string))

export default function ThermalFeeReceipts(){
 const[receipts,setReceipts]=useState<Receipt[]>([]),[students,setStudents]=useState<Student[]>([]),[school,setSchool]=useState<School|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState('')
 const[classes,setClasses]=useState<Record<string,string>>({}),[streams,setStreams]=useState<Record<string,string>>({})
 const studentMap=useMemo(()=>new Map(students.map(s=>[s.id,s])),[students])
 const load=async()=>{setLoading(true);const db=createClient();const[{data:r,error:re},{data:s,error:se},{data:settings,error:ee},{data:c},{data:st}]=await Promise.all([
  db.from('fee_receipts').select('id,receipt_no,payment_id,student_id,amount_paid,balance,payment_method,reference_no,paid_at').order('created_at',{ascending:false}),
  db.from('students').select('id,first_name,middle_name,last_name,admission_number,class_id,stream_id').eq('status','active').order('last_name'),
  db.from('school_settings').select('school_name,address,logo_url,currency').limit(1).maybeSingle(),
  db.from('classes').select('id,name').eq('status','active'),
  db.from('streams').select('id,name').eq('status','active')
 ]);if(re||se||ee)setMessage(re?.message||se?.message||ee?.message||'Could not load fee receipts.');else{setReceipts((r||[]) as Receipt[]);setStudents((s||[]) as Student[]);setSchool((settings||null) as School|null);setClasses(Object.fromEntries((c||[]).map(x=>[x.id,x.name])));setStreams(Object.fromEntries((st||[]).map(x=>[x.id,x.name])))}setLoading(false)}
 useEffect(()=>{load()},[])
 const printReceipt=(r:Receipt)=>{const s=studentMap.get(r.student_id);const schoolName=school?.school_name||'AIC Cathedral Primary School';const address=school?.address||'Gilgil, Nakuru County, Kenya';const currency=school?.currency||'KES';const logo=school?.logo_url||OFFICIAL_LOGO;const className=s?.class_id?classes[s.class_id]||'':'';const streamName=s?.stream_id?streams[s.stream_id]||'':'';const w=window.open('','_blank','width=420,height=800');if(!w)return;const print=()=>w.print();w.document.write(`<!doctype html><html><head><title>School Fees Receipt ${esc(r.receipt_no)}</title><style>@page{size:80mm auto;margin:0}*{box-sizing:border-box}body{width:80mm;margin:0 auto;padding:5mm 4mm;font-family:Arial,sans-serif;color:#111;font-size:11px;line-height:1.25}.center{text-align:center}.logo{display:block;width:28mm;height:28mm;object-fit:contain;margin:0 auto 2mm}.school{font-size:14px;font-weight:900;line-height:1.08;text-transform:uppercase}.address{font-size:9px;margin-top:1mm}.rule{border-top:1px dashed #111;margin:3mm 0}.title{font-size:13px;font-weight:900;text-align:center;text-transform:uppercase}.row{display:flex;justify-content:space-between;gap:4mm;margin:1.4mm 0}.label{font-weight:700}.amount{font-size:18px;font-weight:900}.balance{font-size:14px;font-weight:900}.small{font-size:9px}.thanks{text-align:center;font-weight:700;margin-top:3mm}.code{font-size:10px;font-weight:900;letter-spacing:.5px;text-align:center;margin-top:3mm;word-break:break-all}@media print{body{width:80mm}}
</style></head><body><div class="center"><img class="logo" src="${esc(logo)}" alt="AIC Cathedral school logo" id="school-logo"><div class="school">${esc(schoolName)}</div><div class="address">${esc(address)}</div></div><div class="rule"></div><div class="title">School Fees Payment Receipt</div><div class="rule"></div><div class="row"><span class="label">Receipt No.</span><span>${esc(r.receipt_no)}</span></div><div class="row"><span class="label">Date</span><span>${esc(new Date(r.paid_at).toLocaleDateString('en-KE'))}</span></div><div class="row"><span class="label">Time</span><span>${esc(new Date(r.paid_at).toLocaleTimeString('en-KE'))}</span></div><div class="rule"></div><div class="row"><span class="label">Student</span><span>${esc(nameOf(s))}</span></div><div class="row"><span class="label">Admission</span><span>${esc(s?.admission_number)}</span></div>${className?`<div class="row"><span class="label">Grade</span><span>${esc(className)}</span></div>`:''}${streamName?`<div class="row"><span class="label">Stream</span><span>${esc(streamName)}</span></div>`:''}<div class="rule"></div><div class="row"><span class="label">Payment Method</span><span>${esc(r.payment_method.replace(/^bank_/,'Bank — ').toUpperCase())}</span></div><div class="row"><span class="label">Reference</span><span>${esc(r.reference_no||'—')}</span></div><div class="rule"></div><div class="row"><span>Amount Paid</span><span class="amount">${esc(currency)} ${money(r.amount_paid)}</span></div><div class="row"><span>Remaining Balance</span><span class="balance">${esc(currency)} ${money(r.balance)}</span></div><div class="rule"></div><div class="thanks">Payment received successfully.</div><div class="thanks">Thank you for your payment.</div><div class="code">${esc(r.receipt_no)}</div><div class="small center" style="margin-top:3mm">Keep this receipt for your records.</div><script>const img=document.getElementById('school-logo');let printed=false;const go=()=>{if(printed)return;printed=true;setTimeout(()=>window.print(),150)};if(img.complete)go();else{img.addEventListener('load',go,{once:true});img.addEventListener('error',go,{once:true});setTimeout(go,2000)}</script></body></html>`);w.document.close()}
 const printLatest=()=>receipts[0]&&printReceipt(receipts[0])
 return <section className="card"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',marginBottom:16}}><div><h2 style={{margin:0}}>Small Fee Receipts</h2><p className="muted" style={{margin:'5px 0 0'}}>Automatic school-fee receipts formatted for 58mm/80mm thermal printers. Receipt numbers are generated automatically; A4 receipts remain unchanged.</p></div>{receipts[0]&&<button type="button" className="btn" onClick={printLatest}>Print latest receipt</button>}</div>{message&&<p style={{color:'#b42318',fontSize:13}}>{message}</p>}<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['Receipt No.','Learner','Amount Paid','Remaining Debt','Method','Date','Action'].map(h=><th key={h} style={{textAlign:'left',padding:10}}>{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={7} style={{padding:25}}>Loading receipts…</td></tr>:receipts.length?receipts.map(r=>{const s=studentMap.get(r.student_id);return <tr key={r.id}><td style={{padding:10,fontWeight:700}}>{r.receipt_no}</td><td style={{padding:10}}>{nameOf(s)}<br/><span className="muted" style={{fontSize:12}}>{s?.admission_number||'—'}</span></td><td style={{padding:10}}>KES {money(r.amount_paid)}</td><td style={{padding:10,fontWeight:700}}>KES {money(r.balance)}</td><td style={{padding:10}}>{r.payment_method.replace(/^bank_/,'Bank — ').toUpperCase()}</td><td style={{padding:10}}>{new Date(r.paid_at).toLocaleString('en-KE')}</td><td style={{padding:10}}><button type="button" className="btn secondary" onClick={()=>printReceipt(r)}>Print Receipt</button></td></tr>}) : <tr><td colSpan={7} className="muted" style={{padding:30,textAlign:'center'}}>No fee receipts have been generated yet.</td></tr>}</tbody></table></div></section>
}
