import SimpleCrud from '../_components/simple-crud'
import LeaveApprovalInbox from '../_components/leave-approval-inbox'
import {createClient} from '../../../lib/supabase/server'
import {PrototypePage} from '../_components/prototype-workspace'
export default async function Academic(){const s=await createClient();const{data:{user}}=await s.auth.getUser();const{data:profile}=await s.from('profiles').select('role').eq('id',user?.id||'').maybeSingle();const{data:classes}=await s.from('classes').select('id,name,level').eq('status','active').order('name');const classOptions=(classes||[]).map(c=>({value:c.id,label:`${c.name}${c.level?` — ${c.level}`:''}`}));return <PrototypePage title="Academic Setup" subtitle="Academic years, terms, classes, East/West streams and CBC learning areas" action={<a href="#years" className="prototype-primary-button">+ Add Academic Year</a>} kpis={[{label:'Academic Years',value:'Live',note:'School calendar',tone:'navy'},{label:'Active Terms',value:'Live',note:'Current teaching period',tone:'green'},{label:'Classes',value:(classes||[]).length,note:'Active grades',tone:'blue'},{label:'CBC Areas',value:'Live',note:'Learning areas',tone:'yellow'}]} tabs={[["#years","Academic Years"],["#terms","Terms"],["#classes","Classes & Streams"],["#cbc","CBC Learning Areas"]]}>
<LeaveApprovalInbox />
<section id="years"><SimpleCrud table="academic_years" title="Academic years" fields={[{name:'year',label:'Year',type:'number',required:true},{name:'status',label:'Status',options:['active','inactive','archived']}]} order="year"/></section>
<section id="terms"><SimpleCrud table="terms" title="Terms" roleHint="Choose Term One, Term Two or Term Three. The current academic year is linked automatically." autoActiveAcademicYear fields={[{name:'academic_year_id',label:'Academic year'},{name:'name',label:'Term',required:true,options:['Term One','Term Two','Term Three']},{name:'start_date',label:'Start date',type:'date'},{name:'end_date',label:'End date',type:'date'},{name:'status',label:'Status',options:['active','inactive','archived']}]} /></section>
<section id="classes"><SimpleCrud table="classes" title="Grades / classes" fields={[{name:'name',label:'Grade / Class name',required:true},{name:'level',label:'Level / stage'},{name:'status',label:'Status',options:['active','inactive','archived']}]} /><SimpleCrud table="streams" title="Streams — East / West" fields={[{name:'class_id',label:'Grade / class',required:true,options:classOptions},{name:'name',label:'Stream name',required:true,options:['East','West','A','B','C']}]} /></section>
<section id="cbc"><SimpleCrud table="learning_areas" title="CBC learning areas" fields={[{name:'name',label:'Learning area',required:true},{name:'code',label:'Code'},{name:'category',label:'Category'}]} /></section>
</PrototypePage>}
