'use client'

import {useEffect,useRef,useState} from 'react'

type Props={label:string;value:string;onChange:(value:string)=>void}
const CANVAS_W=600
const CANVAS_H=150

export default function LeaveSignature({label,value,onChange}:Props){
 const canvasRef=useRef<HTMLCanvasElement|null>(null)
 const drawing=useRef(false)
 const [mode,setMode]=useState<'draw'|'type'>('draw')
 const resizeCanvas=()=>{const c=canvasRef.current;if(!c)return;const rect=c.getBoundingClientRect();const ratio=Math.max(1,window.devicePixelRatio||1);c.width=Math.max(320,Math.round(rect.width*ratio));c.height=Math.round(CANVAS_H*ratio);const ctx=c.getContext('2d');if(!ctx)return;ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(0,0,rect.width,CANVAS_H);ctx.lineWidth=2.5;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#172033';if(value.startsWith('data:image/')){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,rect.width,CANVAS_H);img.src=value}}
 useEffect(()=>{resizeCanvas();const fn=()=>resizeCanvas();window.addEventListener('resize',fn);return()=>window.removeEventListener('resize',fn)},[value])
 const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
 const start=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(mode!=='draw')return;e.preventDefault();drawing.current=true;e.currentTarget.setPointerCapture(e.pointerId);const p=point(e);const ctx=e.currentTarget.getContext('2d');if(ctx){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+0.1,p.y+0.1);ctx.stroke()}}
 const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current||mode!=='draw')return;e.preventDefault();const p=point(e);const ctx=e.currentTarget.getContext('2d');if(ctx){ctx.lineTo(p.x,p.y);ctx.stroke()}}
 const finish=()=>{if(!drawing.current)return;drawing.current=false;const c=canvasRef.current;if(!c)return;const sourceW=c.width,sourceH=c.height;const pixels=c.getContext('2d')?.getImageData(0,0,sourceW,sourceH).data;if(!pixels)return;let minX=sourceW,minY=sourceH,maxX=-1,maxY=-1;for(let y=0;y<sourceH;y++){for(let x=0;x<sourceW;x++){if(pixels[(y*sourceW+x)*4+3]>20){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}}}if(maxX<0){onChange('');return}const out=document.createElement('canvas');out.width=CANVAS_W;out.height=CANVAS_H;const outCtx=out.getContext('2d');if(!outCtx)return;const pad=28,sourceWidth=maxX-minX+1,sourceHeight=maxY-minY+1;const scale=Math.min((CANVAS_W-pad*2)/sourceWidth,(CANVAS_H-pad*2)/sourceHeight,1);const drawW=sourceWidth*scale,drawH=sourceHeight*scale;outCtx.imageSmoothingEnabled=true;outCtx.imageSmoothingQuality='high';outCtx.drawImage(c,minX,minY,sourceWidth,sourceHeight,(CANVAS_W-drawW)/2,(CANVAS_H-drawH)/2,drawW,drawH);onChange(out.toDataURL('image/png'))}
 const clear=()=>{const c=canvasRef.current;if(c){const ctx=c.getContext('2d');if(ctx){ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,c.width,c.height)}}onChange('')}
 const typed=value.startsWith('data:image/')?'':value
 return <div className="signature-field"><div className="signature-head"><strong>{label}</strong><div><button type="button" className={mode==='draw'?'sig-tab active':'sig-tab'} onClick={()=>{setMode('draw');setTimeout(resizeCanvas,0)}}>Draw</button><button type="button" className={mode==='type'?'sig-tab active':'sig-tab'} onClick={()=>setMode('type')}>Type name</button></div></div>{mode==='draw'?<><canvas ref={canvasRef} className="signature-canvas" style={{display:'block',width:'100%',height:CANVAS_H,minHeight:CANVAS_H,border:'2px solid #cbd5e1',borderRadius:10,background:'#fff',touchAction:'none',cursor:'crosshair'}} onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish}/><button type="button" className="signature-clear" onClick={clear}>Clear</button></>:<input className="signature-typed" value={typed} onChange={e=>onChange(e.target.value)} placeholder="Enter your name as signature"/>}<style jsx global>{`.signature-image{display:block!important;width:220px!important;height:55px!important;max-width:100%!important;object-fit:contain!important;object-position:left center!important;margin:4px 0 0!important}.typed-signature{display:block!important;width:220px!important;max-width:100%!important;min-height:55px!important;overflow:hidden!important;white-space:nowrap!important;font-family:"Segoe Script","Bradley Hand",cursive!important;font-size:20px!important;font-weight:600!important;line-height:1.15!important;margin:4px 0 0!important;padding:0 0 3px!important;border-bottom:1px solid #172033!important}.permission-signatures>div{min-height:82px!important;max-width:260px!important;overflow:hidden!important;display:flex!important;flex-direction:column!important;align-items:flex-start!important;justify-content:flex-start!important}.permission-signatures{overflow:hidden!important}`}</style></div>
}
