'use client'
import {useEffect,useState} from 'react'
import {createClient} from '../../../lib/supabase/client'

export default function LeaveApprovalInbox(){
 const db=createClient();const[role,setRole]=useState('');const[requests,setRequests]=useState<any[]>([]);const[staff,setStaff]=useState<any[]>([]);const[notes,setNotes]=useState<Record<string,string>>({});const[msg,setMsg]=useState('');const[loading,setLoading]=useState(false)
 const load=async()=>{const{data:{user}}=await db.auth.getUser();if(!user)return;const{data:p}=await db.from('profiles').select('role').eq('id',user.id).maybeSingle();setRole(p?.role||'');const{data:s}=await db.from('staff').select('id,first_name,middle_name,last_name').order('first_name');setStaff(s||[]);const{data:r,error}=await db.from('leave_requests').select('id,staff_id,start_date,end_date,start_time,end_time,reason,status,request_type,approval_role,created_at').eq('status','pending').eq('approval_role','headteacher').order('created_at',{ascending:false});if(error)setMsg(error.message);else setRequests(r||[])}
 useEffect(()=>{load()},[])
 const act=async(id:string,status:'approved'|'rejected')=>{const{data:{user}}=await db.auth.getUser();if(!user)return;setLoading(true);const{error}=await db.from('leave_requests').update({status,approved_by:user.id,decided_at:new Date().toISOString(),decision_note:notes[id]?.trim()||null}).eq('id',id).eq('status','pending');setLoading(false);setMsg(error?.message||`Request ${status}.`);if(!error)await load()}
 const name=(id:string)=>{const x=staff.find(s=>s.id===id);return x?[x.first_name,x.middle_name,x.last_name].filter(Boolean).join(' '):'Staff member'}
 if(!['headteacher','super_admin'].includes(role))return null
 return <section className="prototype-panel" style={{marginTop:18}}><div className="prototype-panel-head"><div><h2>Leave & Short Leave Approvals</h2><p className="muted">Head Teacher approval inbox. Staff off requests are routed to HR.</p></div></div><div className="prototype-panel-body">{msg&&<p className="muted">{msg}</p>}<div className="prototype-table-wrap"><table className="prototype-table"><thead><tr><th>TEACHER</th><th>TYPE</th><th>DATE(S)</th><th>TIME</th><th>REASON</th><th>DECISION NOTE</th><th>ACTION</th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td><strong>{name(r.staff_id)}</strong></td><td>{r.request_type==='short_leave'?'Short Leave':'Leave'}</td><td>{r.start_date}{r.end_date!==r.start_date?` → ${r.end_date}`:''}</td><td>{r.start_time&&r.end_time?`${r.start_time.slice(0,5)} – ${r.end_time.slice(0,5)}`:'—'}</td><td>{r.reason}</td><td><input value={notes[r.id]||''} onChange={e=>setNotes(n=>({...n,[r.id]:e.target.value}))} placeholder="Optional note"/></td><td><button className="btn" disabled={loading} onClick={()=>act(r.id,'approved')}>Approve</button> <button className="btn secondary" disabled={loading} onClick={()=>act(r.id,'rejected')}>Reject</button></td></tr>)}{requests.length===0&&<tr><td colSpan={7} className="prototype-empty">No pending leave or short-leave requests.</td></tr>}</tbody></table></div></div></section>
}
