'use client'
import {useEffect,useState,type FormEvent} from 'react'
import {createClient} from '../../../lib/supabase/client'
type Option=string|{value:string;label:string}
type Field={name:string;label:string;type?:string;required?:boolean;options?:Option[]}
type Props={table:string;title:string;fields:Field[];select?:string;order?:string;roleHint?:string;valueLabels?:Record<string,string>}
export default function SimpleCrud({table,title,fields,select='*',order='id',roleHint,valueLabels={}}:Props){
 const[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[form,setForm]=useState<Record<string,string>>({}),[editing,setEditing]=useState<string|null>(null)
 const load=async()=>{setLoading(true);const{data,error}=await createClient().from(table).select(select).order(order,{ascending:false});if(error)setMessage(error.message);else setRows(data||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 const save=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setMessage('');const payload:any={};fields.forEach(f=>{if(form[f.name]!==undefined&&form[f.name]!==''){if(f.type==='number')payload[f.name]=Number(form[f.name]);else if(f.type==='boolean')payload[f.name]=form[f.name]==='true';else payload[f.name]=form[f.name]}});const q=createClient().from(table);const{error}=editing?await q.update(payload).eq('id',editing):await q.insert(payload);if(error)setMessage(error.message);else{setForm({});setEditing(null);setMessage(editing?'Updated successfully.':'Saved successfully.');await load()}setSaving(false)}
 const edit=(row:any)=>{const next:Record<string,string>={};fields.forEach(f=>{const v=row[f.name];if(v!==null&&v!==undefined)next[f.name]=f.type==='boolean'?(v?'true':'false'):String(v)});setForm(next);setEditing(row.id);setMessage('')}
 const remove=async(id:string)=>{if(!confirm('Delete this record?'))return;const{error}=await createClient().from(table).delete().eq('id',id);setMessage(error?.message||'Deleted.');await load()}
 const cancel=()=>{setEditing(null);setForm({});setMessage('')}
 const displayValue=(f:Field,value:any)=>{if(value===null||value===undefined||value==='')return '—';if(f.type==='boolean')return value?'Yes':'No';if(f.name in valueLabels)return valueLabels[f.name]||String(value);if(f.options){const match=f.options.find(o=>String(typeof o==='string'?o:o.value)===String(value));if(match)return typeof match==='string'?(match==='true'?'Yes':match==='false'?'No':match):match.label}return typeof value==='object'?JSON.stringify(value):String(value)}
 return <section className="card"><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',marginBottom:16}}><div><h2 style={{margin:0}}>{title}</h2>{roleHint&&<p className="muted" style={{margin:'5px 0 0'}}>{roleHint}</p>}</div><span className="muted">{rows.length} records</span></div><form onSubmit={save} style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,marginBottom:20}}>{fields.map(f=><div key={f.name}><label>{f.label}</label>{f.options?<select value={form[f.name]||''} onChange={e=>setForm({...form,[f.name]:e.target.value})} required={f.required}><option value="">Select…</option>{f.options.map(o=>{const v=typeof o==='string'?o:o.value;const l=typeof o==='string'?(o==='true'?'Yes':o==='false'?'No':o):o.label;return <option value={v} key={v}>{l}</option>})}</select>:<input type={f.type==='boolean'?'text':f.type||'text'} value={form[f.name]||''} onChange={e=>setForm({...form,[f.name]:e.target.value})} required={f.required} placeholder={f.label}/>}</div>)}<div style={{display:'flex',alignItems:'end',gap:8}}><button className="btn" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Add record'}</button>{editing&&<button type="button" className="btn secondary" onClick={cancel}>Cancel</button>}</div></form>{message&&<p style={{color:message.includes('successfully')?'#18794e':'#b42318',fontSize:13}}>{message}</p>}<div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{fields.map(f=><th key={f.name} style={{textAlign:'left',padding:10}}>{f.label}</th>)}<th style={{padding:10}}>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={fields.length+1} style={{padding:25}}>Loading…</td></tr>:rows.length?rows.map(row=><tr key={row.id}>{fields.map(f=><td key={f.name} style={{padding:10}}>{displayValue(f,row[f.name])}</td>)}<td style={{padding:10,whiteSpace:'nowrap'}}><button type="button" onClick={()=>edit(row)} style={{background:'transparent',border:0,color:'#0757a6',cursor:'pointer',marginRight:10}}>Edit</button><button type="button" onClick={()=>remove(row.id)} style={{background:'transparent',border:0,color:'#b42318',cursor:'pointer'}}>Delete</button></td></tr>):<tr><td colSpan={fields.length+1} className="muted" style={{padding:30,textAlign:'center'}}>No records yet. Add the first one above.</td></tr>}</tbody></table></div></section>}
